### ISSUE TITLE
Direnv package comparison installs wrong version

### ISSUE THREAD

**Issue by sean-bennett112** [target/lorri#1]
I'm currently on `direnv-2.17.0`(and `nix` 2.1.3 on Darwin), and it looks like `direnv/nix.nix` is installing my current version of `direnv` instead of `2.19.2`.

It looks like `isOlderThan` is determining that here:

```nix
(builtins.compareVersions wantedVersion pkgVersion) == 0
```

And testing that out gives me:

```
nix-repl> (builtins.compareVersions "2.19.2" "2.19.3")
-1

nix-repl> (builtins.compareVersions "2.19.2" "2.19.2")
0

nix-repl> (builtins.compareVersions "2.19.2" "2.17.0")
1
```

Should that line instead be the below?

```nix
(builtins.compareVersions wantedVersion pkgVersion) >= 0
```

Still very much a Nix beginner, though, so it's entirely possible I'm missing something!

**Comment by grahamc** [comment]
Oh dear, I saw this bug, fixed the bug, and forgot to push it. Please test https://github.com/target/lorri/pull/3?

**Comment by sean-bennett112** [comment]
Works like a charm, thanks!
