### ISSUE TITLE
Editor integration

### ISSUE THREAD

**Issue by IvanMalison** [target/lorri#107]
It might be cool to use something like dbus to call into any editors listening using some perscribed namespace (sort of similar to mpris2) so that the editor knows to update the environment without needing to explicitly refresh. This would require changes in lorri and probably a small package that sits on top of existing direnv integrations, but shouldn't be all that hard to do.

Thoughts?

**Comment by Profpatsch** [comment]
Care to elaborate how this works? Bear in mind we don’t have dbus on MacOS.

**Comment by IvanMalison** [comment]
@Profpatsch actually, it is possible to install dbus on macos, though I will agree that it is somewhat non standard.

You can also compile e.g. emacs with dbus support. The idea would be as follows:

- editor plugin registers on dbus on a dbus name with some lorri specific prefix like `org.lorri.Editor` and then an editor specific suffix, or maybe it's pid.
- whenever lorri daemon is done rebuilding a nix-shell, it makes an rpc to every process that is registered with the lorri prefix. I think the only needed argument here would be the relevant path.
- upon receiving this call, the editor plugin then updates the direnv environment it has for that path

Dbus makes this much easier, but its not necessarily a hard requirement. Could also do something with websockets or socket files in a predictable location.

**Comment by Profpatsch** [comment]
That’s more of an upstream feature request for direnv-mode, no?

**Comment by IvanMalison** [comment]
> That’s more of an upstream feature request for direnv-mode, no?

@Profpatsch I don't see how at all. This is targeted specifically at lorri's more asynchronous mode of operation:

- direnv refreshes a particular shell's environment at each prompt, while this would integrate with editors and tell them to update whenever the shell has recomputed to avoid e.g. having to call direnv-update-environemnt
- it would required dbus calls from the lorri daemon side

at least w.r.t the emacs side of things though, it seems that the approach of simply calling in to direnv every time there is a buffer switch is how things currently work, so perhaps this isnt needed.

**Comment by IvanMalison** [comment]
It seems like the answer to this question is simply:

The editor should find the most recent lorri shell every time any buffer change takes place.

**Comment by Profpatsch** [comment]
> at least w.r.t the emacs side of things though, it seems that the approach of simply calling in to direnv every time there is a buffer switch is how things currently work, so perhaps this isnt needed.

Not quite, every time there is a switch between buffers backed by different `.envrc` files.
