### ISSUE TITLE
direnv reload takes up to 13 seconds when changing directories

### ISSUE THREAD

**Issue by IvanMalison** [target/lorri#110]
Haven't done much investigation, but it seems that this is not on the daemon side of things, because it happens even when the rebuild occurs in a much shorter amount of time. I suppose that it could also be a direnv issue, but direnv seems to be running relatively quickly for non lorri expressions. Are there any easy ways to debug this?
```
~/.config/taffybar/taffybar master*
❯ time zsh -c 'direnv reload'
zsh -c 'direnv reload'  0.01s user 0.00s system 102% cpu 0.010 total
direnv: loading .envrc
direnv: ([/nix/store/fvvdirp8mf30241alvbz5y5gqcdansx2-direnv-2.20.0-bin/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
direnv: export +AR +AR_FOR_TARGET +AS +AS_FOR_TARGET +CC +CC_FOR_TARGET +CONFIG_SHELL +CXX +CXX_FOR_TARGET +GETTEXTDATADIRS +GSETTINGS_SCHEMAS_PATH +HOST_PATH +IN_NIX_SHELL +LD +LD_FOR_TARGET +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_x86_64_unknown_linux_gnu_TARGET_HOST +NIX_BINTOOLS_WRAPPER_x86_64_unknown_linux_gnu_TARGET_TARGET +NIX_BUILD_CORES +NIX_BUILD_TOP +NIX_CC +NIX_CC_WRAPPER_x86_64_unknown_linux_gnu_TARGET_HOST +NIX_CC_WRAPPER_x86_64_unknown_linux_gnu_TARGET_TARGET +NIX_CFLAGS_COMPILE +NIX_ENFORCE_NO_NATIVE +NIX_GHC +NIX_GHCPKG +NIX_GHC_DOCDIR +NIX_GHC_LIBDIR +NIX_HARDENING_ENABLE +NIX_INDENT_MAKE +NIX_LDFLAGS +NIX_LOG_FD +NIX_SSL_CERT_FILE +NIX_STORE +NIX_TARGET_BINTOOLS +NIX_TARGET_CC +NIX_TARGET_CFLAGS_COMPILE +NIX_TARGET_LDFLAGS +NM +NM_FOR_TARGET +OBJCOPY +OBJCOPY_FOR_TARGET +OBJDUMP +OBJDUMP_FOR_TARGET +PKG_CONFIG_PATH +RANLIB +RANLIB_FOR_TARGET +READELF +READELF_FOR_TARGET +SIZE +SIZE_FOR_TARGET +SOURCE_DATE_EPOCH +SSL_CERT_FILE +STRINGS +STRINGS_FOR_TARGET +STRIP +STRIP_FOR_TARGET +TARGET_AR +TARGET_AS +TARGET_CC +TARGET_CXX +TARGET_LD +TARGET_NM +TARGET_OBJCOPY +TARGET_OBJDUMP +TARGET_RANLIB +TARGET_READELF +TARGET_SIZE +TARGET_STRINGS +TARGET_STRIP +buildInputs +builder +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +extraClosure +installPhase +name +nativeBuildInputs +origArgs +origBuilder +origExtraClosure +origOutputs +origPATH +origSystem +out +outputs +patches +phases +preHook +propagatedBuildInputs +propagatedNativeBuildInputs +shell +stdenv +strictDeps +system ~GDK_PIXBUF_MODULE_FILE ~LANG ~LOCALE_ARCHIVE ~PATH

~/.config/taffybar/taffybar master* 13s
❯                        ~/.config/taffybar/taffybar
direnv: loading .envrc
```

**Comment by ocharles** [comment]
I was experiencing the same thing today. I spent some time debugging with @grahamc. It turnedo out that `direnv export zsh` was taking a long time, if ran in an environment that doesn't have direnv hooks setup. I ran `strace -f` on this, and we see:

```
[pid  8992] execve("/run/current-system/sw/bin/bash", ["/run/current-system/sw/bin/bash", "--noprofile", "--norc", "-c", "eval \"$(\"/nix/store/r65421l75zr7"...], 0xc0001e0000 /* 89 vars */ <unfinished ...>
```

This `execve` is bash with some path into `direnv`s store path. It then seems to sit there for 10 seconds doing things like [this](https://gist.github.com/ocharles/b5c33636fca23d3f04d5f1948d9c1feb) over and over again:

```
[pid  9195] ioctl(0, TCGETS, 0x7ffefd986d40) = -1 ENOTTY (Inappropriate ioctl for device)
[pid  9195] lseek(0, 0, SEEK_CUR)       = 2144
[pid  9195] read(0, "P", 1)             = 1
[pid  9195] read(0, "Y", 1)             = 1
[pid  9195] read(0, "T", 1)             = 1
[pid  9195] read(0, "H", 1)             = 1
[pid  9195] read(0, "O", 1)             = 1
[pid  9195] read(0, "N", 1)             = 1
[pid  9195] read(0, "P", 1)             = 1
[pid  9195] read(0, "A", 1)             = 1
[pid  9195] read(0, "T", 1)             = 1
[pid  9195] read(0, "H", 1)             = 1
[pid  9195] read(0, "\0", 1)            = 1
[pid 9195] ioctl(0, TCGETS, 0x7ffefd986e50) = -1 ENOTTY (Inappropriate ioctl for device)
```

We finally found out that it's the `varmap` file that's the culprit. My `varmap` in my `.cache/lorri` looked like this: https://gist.github.com/ocharles/fe9de3f131d9cee68cb162f42804ca46

If I manually remove the symlinked directory in `.cache` and recreate it without `varmap`, `lorri` is snappy again.

**Comment by IvanMalison** [comment]
I had a similar issue with a varmap file with a crazy number of repeated entries. I think the question now becomes: what is causing/creating these files with so much repeated stuff?

https://gist.github.com/39ca816d7e71d213a79bfb0535924dfe

**Comment by IvanMalison** [comment]
Here's another one with a crazy number of repeated entries. Seems like there is probably some deduplication logic missing somewhere

./.cache/lorri/gc_roots/70d0c5596c6cc260f9e633508404887b/gc_root/build-0/varmap-v1

**Comment by IvanMalison** [comment]
Okay, so I'm not super familiar with what is going on here, but I think the issue may simply be that here:

https://github.com/target/lorri/blob/80ca3e7c12f74af035cdeff289ba2aa3c8950cb2/src/logged-evaluation.nix#L91

we unconditionally add to varmap, when really, what we should do is check to see if the variable is in varmap, and only actually append it to the file if it isn't already there.

Looks like @grahamc wrote most of this code. Can you confirm that this is the approach that should be used?

**Comment by ocharles** [comment]
I nuked my cache, rebuilt `lorri`, and things are good now :+1:
