### ISSUE TITLE
Include human-panic or similar

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#114]
https://github.com/rust-cli/human-panic

`human-panic` captures panics, prints them (and more information) to a file and prints a message which asks the user to submit an issue with the contents of the panic file

It has a few dependencies I’m not sure about, but we should include the gist of it into lorri.

**Comment by johnchildren** [comment]
Looks like it might be possible to replicate some of this functionality directly using the standard library's [set_hook](https://doc.rust-lang.org/std/panic/fn.set_hook.html) as listed in their README. This way it would be possible to have a more customized message without the extra dependencies (potentially).

I'm interested in picking this up over the weekend if that is of interest, alternatively using human-panic looks like it would be straightforward enough. Do you have any specific requirements about what kind of information you would like to include in the panic message?

**Comment by Profpatsch** [comment]
After some deliberation (and looking at the `human_panic` source), I’ve arrived at the conclusion that we should use the `human_panic` crate, and create a few issues/PRs to improve it.

The only dependencies that are a bit questionable are `termcolor` and `failure`.
`termcolor` is only used to color the output red, which I’d argue is not really worth a dependency that wraps terminal behavior.
`failure` is a bit strange, especially because I didn’t see the code use it in any way.

So let’s just add `human_panic` for now and add a tracking issue for removing these deps. We already depend on `termcolor` via `env_logger` anyway.

**Comment by johnchildren** [comment]
Thanks! I have made a PR to human-panic https://github.com/rust-cli/human-panic/pull/63 which should update a few things and (if accepted) it seems that the dependency on `failure` was unnecessary as well as pruning a few other crates that weren't being used.

Unfortunately the version of human-panic in crates.io has not yet been updated for a version of termcolor >= 1.0 so two versions of the crate would be introduced if I were to add the current version of the crate, but potentially could be done for now and then updated when a new version is released?

**Comment by Profpatsch** [comment]
Great work!



> Unfortunately the version of human-panic in crates.io has not yet been updated for a version of termcolor >= 1.0 so two versions of the crate would be introduced if I were to add the current version of the crate, but potentially could be done for now and then updated when a new version is released?

In the optimal case `human_panic` would have a config option that disables term colors (I don’t think they are needed to achieve the libraries goal, and coloring terminal output for errors usually interferes with users setup anyway). But if they definitely want to keep those, it shouldn’t be that much work to update to >1.0, right? It’s just three lines in the code, which sets the buffer color to red.

**Comment by johnchildren** [comment]
>it shouldn’t be that much work to update to >1.0, right? It’s just three lines in the code, which sets the buffer color to red.

So the interesting part is that they already updated it but just haven't pushed a new version to crates.io, which is what I was trying to say a little clumbsily: https://github.com/rust-cli/human-panic/blob/master/Cargo.toml#L18

**Comment by johnchildren** [comment]
Doesn't seem to have been a response from the maintainers yet, would it be worth exploring alternatives?

**Comment by Profpatsch** [comment]
I pinged the members of the rust-cli toplevel orga. The people originally working on `human-cli` are probably gone by now.

**Comment by Profpatsch** [comment]
Awesome, the PR was merged, now we just have to find a way to include it into our project.

Is it possible to pin unreleased versions in the cargo file?

**Comment by johnchildren** [comment]
>Is it possible to pin unreleased versions in the cargo file?

I think you can through git if that works? If so I can try to make PR tomorrow for this functionality.

**Comment by curiousleo** [comment]
@Profpatsch I think this issue can be closed now.
