### ISSUE TITLE
`lorri direnv` should take the shell.nix file as argument

### ISSUE THREAD

**Issue by sgraf812** [target/lorri#116]
I'm working on GHC, where there's https://github.com/alpmestan/ghc.nix to provision a proper build environment. I have checked that repository out in ~/ghc/nix, alongside my GHC checkouts. So, normally a build command looks like `nix-shell --pure ../nix --run "build/hadrian.sh --flavour=quick test"`. Quite a mouthful! I was hoping I could fire up lorri like `eval $(lorri direnv ../nix/default.nix)`, but apparently that doesn't work.

**Comment by sgraf812** [comment]
Wait... So, ghc.nix isn't probably gonna change that frequently. So I'm probably better off with taking what `lorri watch` produces and modify it so that it works for my use case and use that as my .envrc, right?

**Comment by sgraf812** [comment]
OK, `ln -s ../nix/default.nix shell.nix` seems to work for now, at least it builds something in ~/.cache. But apparently although I get "direnv: loading .envrc" when entering the directory in my zsh shell, The environment is rather the same as before; None of the build dependencies are present. Weird.

**Comment by Profpatsch** [comment]
Internally, I refactored everything to not depend on `shell.nix` anymore, so we can add a `--shell-file` option to `lorri watch`/`lorri direnv` at any time.

**Comment by jfroche** [comment]
merged, this issue can be fixed
