### ISSUE TITLE
Crash when nix files reference a nonexistent file

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#121]
[Side note: I discovered what caused the unrecoverable error. My shell.nix was referencing a nonexistent file. With the same files, `nix-shell` reported:

```
$ nix-shell
error: getting status of '/home/b/RELEX/repos/the-repo/local-dev-environment/_generated-nix/google-oauth2.nix': No such file or directory
(use '--show-trace' to show detailed location information)
```

]

_Originally posted by @chreekat in https://github.com/target/lorri/issues/120#issuecomment-516424672_

**Comment by grahamc** [comment]
Let's verify the paths exist at this point: https://github.com/target/lorri/blob/f93989b34fe605798ecd841cea9c0ba6f8e00f91/src/builder.rs#L102-L104

and we'll want to do the same for the `EvalSource` variant from #58.

**Comment by Profpatsch** [comment]
I cannot reproduce on #117; build errors are fundamentally `Recoverable` now. #120 is still a problem, though.

**Comment by chreekat** [comment]
Nice!

**Comment by Profpatsch** [comment]
Ah, not quite; #117 does fix the problem for nix-instantiate, but it still happens in case of `nix-build` errors.
