### ISSUE TITLE
Failing to build Lorri when behing a proxy

### ISSUE THREAD

**Issue by teehemkay** [target/lorri#124]
I'm trying to build `lorri` at work. It's failing with the message below. We're behind a proxy my guess is that I need to somehow setup the HTTP(S)_PROXY environment variables (I'm using Darwin-nix with multi-user Nix and the nix-daemon is correctly setup with the proxy environment vars)

```
source root is lorri
patching sources
installing
    Updating crates.io index
warning: spurious network error (2 tries remaining): curl error: Could not resolve host: github.com
; class=Net (12)
warning: spurious network error (1 tries remaining): curl error: Could not resolve host: github.com
; class=Net (12)
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  curl error: Could not resolve host: github.com
```

I think the problem comes from rust (or some related utilities) trying to access the internet from the build sandbox. 
For that, the appropriate environment variables (HTTP(S)_PROXY) need to be setup in the build sandbox environment.
I'm not sure how to do that.

Thank you

**Comment by Profpatsch** [comment]
It looks to me like we are correctly setting the right proxy variables in `fetchcargo` (which is used by us to build lorri): 

https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/fetchcargo.nix#L61
which is this list of proxy variables: https://github.com/NixOS/nixpkgs/blob/master/lib/fetchers.nix

Do you know how we could reproduce your environment to have a chance at reproduction?

**Comment by teehemkay** [comment]
Ah ah, thanks for the pointer!
The vars are defined with uppercase letters in my config, so maybe that's the problem.
I'll test adding the lowercase version tomorrow at work and let you know if it fixes the issue.

**Comment by teehemkay** [comment]
The different casing of the environment variables was indeed the problem.
I've added lower cased versions and now building `lorri` works like a cinch.
Thank you so much for your help Profpatsch!

**Comment by Profpatsch** [comment]
Awesome, I think we can close this then.

**Comment by teehemkay** [comment]
Yes.  I’ll go ahead and close it.
