### ISSUE TITLE
Can't reproduce build from another computer: ...-runtime-closure.nix: No such file

### ISSUE THREAD

**Issue by justinwoo** [target/lorri#125]
I'm trying to build a project that I have on my laptop, but it doesn't work on my desktop. Overall same hardware, same platform:

```
 $ lorri watch
Started
Failure(
    BuildExitFailure {
        log_lines: [
            // a bunch of lines
            "instantiated \'spago2nix\' -> \'/nix/store/kjpb6gxjjy2sr1ba9ifqc8g2qnffs2ch-spago2nix.drv\'",
            "instantiated \'nix-shell\' -> \'/nix/store/0dzm2lc4ixrh64y9bbjgfh819k0q12p7-nix-shell.drv\'",
            "error: getting status of \'/nix/store/1manqjxzqpriw9hq5lfqlc6pgdwfmgbh-runtime-closure.nix\': No such file or directory",
            "(use \'--show-trace\' to show detailed location information)",
        ],
    },
)
```

**Comment by justinwoo** [comment]
Yeah, the fix is that I needed to run the nix-shell in this project to get the closure. Afterwards, seems to work fine.

**Comment by Profpatsch** [comment]
That should never be necessary though. Can you reproduce the problem after it worked once?

**Comment by justinwoo** [comment]
Don't think so. Just requires nix-shell to be called in the lorri project once, so there's just some runtime deps that aren't checked for when only using the binary directly e.g. https://github.com/justinwoo/my-lorri/blob/239f2b911124e6a999b7b2d0da1a3f3738cb97b8/default.nix

reproduced the issue on my coworker's computer and indeed, once we ran the nix-shell and had everything in the universe build as a result of the nix shell init, the patched binary worked

**Comment by justinwoo** [comment]
This would be reproducible in CI though

**Comment by Profpatsch** [comment]
I have no idea how we would reproduce this. Closing for now.

**Comment by justinwoo** [comment]
It's something that will come up with binary distributions in the future. It would be nice if the closures were vendored and run once. Just something that will come up later though.
