### ISSUE TITLE
is it safe to run Lorri as a system daemon?

### ISSUE THREAD

**Issue by BrianHicks** [target/lorri#14]
I'd really like to run `lorri watch` once and then not have to worry about it when I switch between projects. Is that safe, as designed? I think it'd work looking at where files end up, but I'm not 100% sure if that's incidental or on purpose.

I guess if it's on purpose, I'd also like a way to query status in my shell or editor—e.g. `lorri status` figures out if the relevant process is idle, building, or in error. That way I can integrate it into my prompt. (edit: although I'd like that regardless of if it's a per-project or system daemon, so LMK if it would be more helpful for me to open another issue with more details to track separately?)

**Comment by Profpatsch** [comment]
There’s some discussion going on in https://github.com/target/lorri/issues/2, I’ll migrate your comment there.

**Comment by BrianHicks** [comment]
ah, thank you!
