### ISSUE TITLE
IN_NIX_SHELL is set to 1 instead of "pure" or "impure"

### ISSUE THREAD

**Issue by bbigras** [target/lorri#140]
I'm trying to add nix-shell support to a prompt tool and it seems lorri sets IN_NIX_SHELL to 1 instead of "pure" or "impure".

Someone on irc said that it should be set to "pure".

**Comment by Profpatsch** [comment]
```
> nix-shell -p --command 'printenv IN_NIX_SHELL'
impure
> nix-shell -p --pure --command 'printenv IN_NIX_SHELL'
pure
```

This must have changed recently, because I can only ever remember it being `1`.
