### ISSUE TITLE
lorri watch panic-attack when eval includes non-existant path (typo)

### ISSUE THREAD

**Issue by dtzWill** [target/lorri#15]
While editing a `shell.nix` being monitored by lorri, I accidentally wrote `import ./default { }` :innocent: instead of `import ./. {}` or `import ./default.nix {}`-- which of course causes a Nix eval error but lorri seems to die trying to deal with the path that doesn't exist.

Lorri just was trying to watch things for me and in return I cause it to panic and die :(.  Poor lorri.  Sokay these guys can fix you up, they're the best! ;)

**Comment by Profpatsch** [comment]
I think that’s the same as https://github.com/target/lorri/issues/50.

**Comment by Profpatsch** [comment]
Closing in favor of #50 (which I also marked as good first issue)
