### ISSUE TITLE
"Please start `lorri daemon`", but it's already running

### ISSUE THREAD

**Issue by jonas-schievink** [target/lorri#151]
On my system, `lorri direnv` is complaining that the daemon isn't running, even though it is (started as a systemd service). It also seems to recognize this, because `lorri daemon` fails with 

> Another daemon is already listening on the socket at /run/user/1000/lorri/daemon.socket. We are currently only allowing one daemon to be running at the same time.

This seems weird, maybe `lorri direnv` should output more info so the error can be diagnosed easier?

**Comment by gilligan** [comment]
Yeah, so the message in this case is misleading. The daemon is indeed running but hasn't finished (and has never before) evaluated your shell.nix.

@Profpatsch maybe as a first "minimal effort, medium benefit" kind of step the message could be adjusted to point out this ambiguity? Which isn't an actual solution to the problem but might be useful to users anyhow i guess (?)

**Comment by jonas-schievink** [comment]
My problem specifically seems to be that `NIX_PATH` isn't set correctly, so the daemon fails to build anything (I'm using Nix on Arch Linux and had to manually fix `NIX_PATH` for my user).

**Comment by Profpatsch** [comment]
We need to change the message, it shows up in both of these cases:

* The daemon is not running
* The daemon has never successfully built the repository before
