### ISSUE TITLE
Lorri sets PWD

### ISSUE THREAD

**Issue by roberth** [target/lorri#153]
`PWD` is set to `/build`. This can be problematic for scripts that follow the `lorri` invocation. It does not appear to propagate all the way to the user shell.

`.envrc`:
```
eval "$(lorri direnv)"

echo "PWD:"
echo $PWD
echo "pwd:"
pwd
```

Result:
```
$ direnv allow
direnv: loading .envrc
PWD:
/build
pwd:
/home/user/h/nix-pre-commit-hooks
```

### Proposed solution

 Filter out `PWD` from the `lorri direnv` command.

Probably [other variables](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html) are affected too.

**Comment by grahamc** [comment]
Reading the linked page (https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html) showed the following additional variables we may want to not set:


- OLDPWD
- SHELL
- PWD

**Comment by johnae** [comment]
This actually affects the shellHook since $PWD in the shellHook is set to /build rather than the expected directory you've just cd:ed into. This affects the ability to set environment variables pointing to this directory. Just an example is that I have my own package collection and so I want to set NIX_PATH while developing so that I can try stuff out easily - with direnv + nix-shell this worked, not so with lorri unfortunately.

**Comment by grahamc** [comment]
Unfortunately, since the shellHook is executed as part of the build, that is going to remain true.

If you want to set environment variables, you can do so directly in the derivation itself:

```
pkgs.mkShell {
   NIX_PATH = toString ../nixpkgs;
}
```

**Comment by johnae** [comment]
Ok thanks, that does seem workable in this case.

**Comment by Profpatsch** [comment]
Don’t forget the `toString`, otherwise nix copies the path to the store every time.

**Comment by mjlbach** [comment]
This doesn't seem to work for $PATH
```
let
  pkgs = import <nixpkgs> {};
in
pkgs.mkShell {
  PATH= toString "$PATH:$(pwd)/_build/pip_packages/bin:$PATH";
  PYTHONPATH= toString "$(pwd)/_build/pip_packages/lib/python3.7/site-packages:$PYTHONPATH";
  buildInputs = with pkgs.python3.pkgs; [
    pip
    numpy
    setuptools
  ];
  shellHook = ''
    export LD_LIBRARY_PATH=${pkgs.linuxPackages.nvidia_x11}/lib:${pkgs.stdenv.cc.cc.lib}/lib:${pkgs.cudatoolkit_10_1}/lib:${pkgs.cudnn_cudatoolkit_10_1}/lib:${pkgs.cudatoolkit_10_1.    lib}/lib:$LD_LIBRARY_PATH
    alias pip="PIP_PREFIX='$(pwd)/_build/pip_packages' TMPDIR='$HOME' \pip"
    unset SOURCE_DATE_EPOCH
  '';
}
```

I'm also wondering how to handle things like LD_LIBRARY path (for some reason, moving it under mkShell fails to expand $LD_LIBRARY_PATH) and aliases

**Comment by Profpatsch** [comment]
> This doesn't seem to work for $PATH

yeah, unfortunately one can only add variables or overwrite them.

So far people have been using it by either
- Using `lorri shell` which sources `shellHook`
- Adding these things to `.envrc` so they are set up by direnv

@grahamc can’t we expose some small DSL like `lorriSetup = [ (appendToEnv ":" "PATH" "somepath") ]` which are forwarded to the runtime setup?

**Comment by mjlbach** [comment]
@Profpatsch I still have the problem when using shell, as if I set path in shellHook appends my path relative to /build/
```
shellHook = ''
    export PATH="$(pwd)/_build/pip_packages/bin:$PATH"
''
```
Results in /build/_build/pip_packages/bin:$PATH instead of relative to the wd

**Comment by Profpatsch** [comment]
@mjlbach can you open a new issue for this?

**Comment by mjlbach** [comment]
@Profpatsch done, sorry that veered off issue

**Comment by adamlwgriffiths** [comment]
I keep running into this issue and forgetting the resolution.

I just want to clearly state the issue/fix for anyone else coming across this(and myself).

When using Lorri instead of nix-shell or direnv, variables like `$PWD` are relative to `/build` instead of the nix-shell directory.
The solution for now is to use the variable `$(pwd)` instead.

Eg.
```
    shellHook = ''
        export LD_LIBRARY_PATH="$PWD/lib:$LD_LIBRARY_PATH"
    ''
```
becomes
```
    shellHook = ''
        export LD_LIBRARY_PATH="$(pwd)/lib:$LD_LIBRARY_PATH"
    ''
```
