### ISSUE TITLE
Lorri fails to build on syntax error in lorri-keep-env-hack

### ISSUE THREAD

**Issue by scoates** [target/lorri#159]
When I enter an `allow`ed direnv with a simple `shell.nix`:

```
sean@sarcasm lorri-test % cat shell.nix
with import <nixpkgs> {};
stdenv.mkDerivation rec {
  name = "test-frontend";
  env = buildEnv { name = name; paths = buildInputs; };
  buildInputs = [
    python37Full
    python37Packages.virtualenv
    python37Packages.pip
    pipenv
  ];
}
sean@sarcasm lorri-test % cat .envrc
eval "$(lorri direnv)"
#unset SSL_CERT_FILE
sean@sarcasm lorri-test %
```

The lorri daemon fails like so:

```
[2019-09-29T15:27:01Z INFO  lorri::daemon] pinged with /Users/sean/tmp/lorri-test/shell.nix
Started
thread '<unnamed>' panicked at 'Unrecoverable error!
Build(
    Build(
        Build(
            ExecutionFailed(
                Output {
                    status: ExitStatus(
                        ExitStatus(
                            256
                        )
                    ),
                    stdout: "",
                    stderr: "error: syntax error, unexpected \',\', expecting \')\', at /nix/store/6ly43zjg6mji2xgn2hd9szi4kxjcwmd5-lorri-keep-env-hack-test-frontend.drv:1:15\n"
                }
            )
        )
    )
)', src/build_loop.rs:83:56
```

It is indeed `nix-build` that's failing:

```
sean@sarcasm lorri-test % nix-build /nix/store/6ly43zjg6mji2xgn2hd9szi4kxjcwmd5-lorri-keep-env-hack-test-frontend.drv
error: syntax error, unexpected ',', expecting ')', at /nix/store/6ly43zjg6mji2xgn2hd9szi4kxjcwmd5-lorri-keep-env-hack-test-frontend.drv:1:15
```

Here's [`/nix/store/6ly43zjg6mji2xgn2hd9szi4kxjcwmd5-lorri-keep-env-hack-test-frontend.drv`](https://paste.website/p/69f6dd61-17e6-41f6-9ce2-b7816f792107.txt).

I realize this isn't a general problem, but this is happening to what seems like all of my nix shells on my machine (which is MacOS Catalina Beta).

Lorri is up to date with git master (via `self-update`).

In case it matters, my nix-channel is:

```
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

and:

```
nix-env (Nix) 2.3
```

Very happy to provide any extra info; just not sure where to go next.

**Comment by Profpatsch** [comment]
@regnat noticed that this happens because we are using `nix-build /nix/store/….drv` instead of `nix-store --realise /nix/store/….drv`, and the nix detection for whether something is a drv file is apparently broken for some versions.

**Comment by Profpatsch** [comment]
We’ll have to restructure the way we call nix a bit, so I can’t promise a quick fix.

> Lorri is up to date with git master (via `self-update`).

Is your lorri on `master` or on `rolling-release`? I don’t think we have the instantiate/build split on `rolling-release` yet.

**Comment by scoates** [comment]
I can do any of those, if it'll help me (-:

I misspoke, and I'm actually on `builder-add-transitive-source-detection-tests`, right now.

**Comment by Profpatsch** [comment]
Haha, now it also appears on our CI: https://travis-ci.org/target/lorri/jobs/592683623#L2635

**Comment by scoates** [comment]
This seems to be working on `master` (actually `master` for me, now).
