### ISSUE TITLE
panic if /nix/var/nix/gcroots/per-user/$USER does not exist

### ISSUE THREAD

**Issue by dudebout** [target/lorri#17]
```
 $ lorri -v watch                                                                                                
Started                                                                                                                                 
thread '<unnamed>' panicked at 'Builder failed: AddRoot(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', src/
build_loop.rs:81:29                                                                                                                     
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                                                                      
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:1009:5
```
With debug logging, I found out this was due to missing `/nix/var/nix/gcroots/per-user/$USER` (https://github.com/target/lorri/blob/master/src/roots.rs#L32) which seems to happen on a single-user non-NixOS install of nix.

**Comment by sgraf812** [comment]
Other projects have similar problems. Note how home-manager requires the user to create that directory: https://github.com/rycee/home-manager#installation

**Comment by dudebout** [comment]
I have similarly added a note in the readme in https://github.com/target/lorri/pull/21

**Comment by Profpatsch** [comment]
Can you create this directory without root access? If so, we should create it automatically.

**Comment by sgraf812** [comment]
I don't think so. Well, at least not unless you `chown`ed it before.

**Comment by grahamc** [comment]
It should be possible, out of the box, to create a directory without sudo:

```
[grahamc@Petunia:~]$ ls -la /nix/var/nix/profiles/../gcroots/per-user 
total 42
drwxrwxrwt 4 root    root   4 Jan 25 19:51 .
drwxr-xr-x 5 root    root   8 Mar 29 08:56 ..
drwxr-xr-x 2 grahamc users 50 Apr  2 12:48 grahamc
drwxr-xr-x 2 root    root   2 Jan 25 19:45 root
```

**Comment by grahamc** [comment]
A weird thing is this dir should exist already in both [single-user](https://github.com/NixOS/nix/blob/41ba5135e0a2d9940c4e8cbedff44eb1a47af782/scripts/nix-profile.sh.in#L37) and [daemon](https://github.com/NixOS/nix/blob/41ba5135e0a2d9940c4e8cbedff44eb1a47af782/scripts/nix-profile-daemon.sh.in#L37) installations.

It feels like a bug in how Nix is installed on your systems... at any rate, let's go ahead and create it here.

**Comment by dudebout** [comment]
This was added in April 2016:
https://github.com/NixOS/nix/commit/af4fb6ef6169b292c7f54e4278c896cb453c56c5
