### ISSUE TITLE
Lorri starts nix-builds in a loop

### ISSUE THREAD

**Issue by johnae** [target/lorri#176]
I've started using lorri from tip of master because of the SSL issues in earlier builds and some other fixes. Since then I've seen my cpu usage spike a lot. Afaict it is lorri, launching nix-builds over and over again. This happens very often, probably several times an hour. I end up restarting lorri which gets rid of those builds (for a while), here's an excerpt from the systemd journal:

```
-- Logs begin at Sat 2019-04-27 23:44:07 CEST. --
Oct 16 14:01:47 europa lorri[923]:     BuildResults {
Oct 16 14:01:47 europa lorri[923]:         output_paths: OutputPaths {
Oct 16 14:01:47 europa lorri[923]:             shell_gc_root: RootPath(
Oct 16 14:01:47 europa lorri[923]:                 "/home/john/.cache/lorri/gc_roots/3f193d3e7cddce96a26099d2979cb202/gc_root/shell_gc_root"
Oct 16 14:01:47 europa lorri[923]:             )
Oct 16 14:01:47 europa lorri[923]:         }
Oct 16 14:01:47 europa lorri[923]:     }
Oct 16 14:01:47 europa lorri[923]: )
Oct 16 14:01:47 europa lorri[923]: Started
Oct 16 14:01:47 europa nix-daemon[8151]: accepted connection from pid 15039, user john (trusted)
Oct 16 14:01:48 europa lorri[923]: Completed(
Oct 16 14:01:48 europa lorri[923]:     BuildResults {
Oct 16 14:01:48 europa lorri[923]:         output_paths: OutputPaths {
Oct 16 14:01:48 europa lorri[923]:             shell_gc_root: RootPath(
Oct 16 14:01:48 europa lorri[923]:                 "/home/john/.cache/lorri/gc_roots/3f193d3e7cddce96a26099d2979cb202/gc_root/shell_gc_root"
Oct 16 14:01:48 europa lorri[923]:             )
Oct 16 14:01:48 europa lorri[923]:         }
Oct 16 14:01:48 europa lorri[923]:     }
Oct 16 14:01:48 europa lorri[923]: )
Oct 16 14:01:48 europa lorri[923]: Started
Oct 16 14:01:48 europa nix-daemon[8151]: accepted connection from pid 15052, user john (trusted)
Oct 16 14:01:49 europa lorri[923]: Completed(
Oct 16 14:01:49 europa lorri[923]:     BuildResults {
Oct 16 14:01:49 europa lorri[923]:         output_paths: OutputPaths {
Oct 16 14:01:49 europa lorri[923]:             shell_gc_root: RootPath(
Oct 16 14:01:49 europa lorri[923]:                 "/home/john/.cache/lorri/gc_roots/3f193d3e7cddce96a26099d2979cb202/gc_root/shell_gc_root"
Oct 16 14:01:49 europa lorri[923]:             )
Oct 16 14:01:49 europa lorri[923]:         }
Oct 16 14:01:49 europa lorri[923]:     }
Oct 16 14:01:49 europa lorri[923]: )
Oct 16 14:01:49 europa lorri[923]: Started
Oct 16 14:01:49 europa nix-daemon[8151]: accepted connection from pid 15065, user john (trusted)
Oct 16 14:01:49 europa lorri[923]: Completed(
Oct 16 14:01:49 europa lorri[923]:     BuildResults {
Oct 16 14:01:49 europa lorri[923]:         output_paths: OutputPaths {
Oct 16 14:01:49 europa lorri[923]:             shell_gc_root: RootPath(
Oct 16 14:01:49 europa lorri[923]:                 "/home/john/.cache/lorri/gc_roots/3f193d3e7cddce96a26099d2979cb202/gc_root/shell_gc_root"
Oct 16 14:01:49 europa lorri[923]:             )
```

**Comment by mmlb** [comment]
I'm able to easily reproduce this by
1. killing lorri
1. cd to a direnv dir
1. wait for lorri to finish and direnv to source env
1. cd out
1. cd into a different direnv enable dir
1. lorri runs a build
1. lorri starts to loop running of builds of things its been told to watch

I've noticed that when the loop starts going wrong `Started` is logged twice
```
> ~> journalctl --user -fu lorri.service | grep -e 'Started\s*$' -e gc_roots
Oct 28 15:51:24: Started
Oct 28 15:51:27:                 "/home/manny/.cache/lorri/gc_roots/fdf0f8d1169cdb49581245fd32ab921a/gc_root/shell_gc_root"
Oct 28 15:51:33: Started
Oct 28 15:51:33: Started
Oct 28 15:51:34:                 "/home/manny/.cache/lorri/gc_roots/14d16d2f4ecfaaad1d2305ac8b6280b4/gc_root/shell_gc_root"
Oct 28 15:51:35: Started
Oct 28 15:51:35:                 "/home/manny/.cache/lorri/gc_roots/fdf0f8d1169cdb49581245fd32ab921a/gc_root/shell_gc_root"
Oct 28 15:51:35: Started
Oct 28 15:51:37:                 "/home/manny/.cache/lorri/gc_roots/14d16d2f4ecfaaad1d2305ac8b6280b4/gc_root/shell_gc_root"
Oct 28 15:51:37: Started
Oct 28 15:51:38: Started
Oct 28 15:51:38:                 "/home/manny/.cache/lorri/gc_roots/fdf0f8d1169cdb49581245fd32ab921a/gc_root/shell_gc_root"
Oct 28 15:51:38: Started
Oct 28 15:51:38:                 "/home/manny/.cache/lorri/gc_roots/14d16d2f4ecfaaad1d2305ac8b6280b4/gc_root/shell_gc_root"
Oct 28 15:51:38: Started
Oct 28 15:51:39:                 "/home/manny/.cache/lorri/gc_roots/14d16d2f4ecfaaad1d2305ac8b6280b4/gc_root/shell_gc_root"
Oct 28 15:51:39: Started
Oct 28 15:51:39:                 "/home/manny/.cache/lorri/gc_roots/0395f4221b81258ed77b68e21324cddc/gc_root/shell_gc_root"
Oct 28 15:51:40: Started
Oct 28 15:51:40:                 "/home/manny/.cache/lorri/gc_roots/fdf0f8d1169cdb49581245fd32ab921a/gc_root/shell_gc_root"
Oct 28 15:51:40: Started
Oct 28 15:51:40:                 "/home/manny/.cache/lorri/gc_roots/14d16d2f4ecfaaad1d2305ac8b6280b4/gc_root/shell_gc_root"
Oct 28 15:51:40: Started
Oct 28 15:51:42:                 "/home/manny/.cache/lorri/gc_roots/14d16d2f4ecfaaad1d2305ac8b6280b4/gc_root/shell_gc_root"
Oct 28 15:51:42: Started
Oct 28 15:51:42:                 "/home/manny/.cache/lorri/gc_roots/0395f4221b81258ed77b68e21324cddc/gc_root/shell_gc_root"
Oct 28 15:51:42: Started
Oct 28 15:51:43:                 "/home/manny/.cache/lorri/gc_roots/fdf0f8d1169cdb49581245fd32ab921a/gc_root/shell_gc_root"
Oct 28 15:51:43: Started
Oct 28 15:51:43:                 "/home/manny/.cache/lorri/gc_roots/14d16d2f4ecfaaad1d2305ac8b6280b4/gc_root/shell_gc_root"
Oct 28 15:51:43: Started
Oct 28 15:51:44:                 "/home/manny/.cache/lorri/gc_roots/0395f4221b81258ed77b68e21324cddc/gc_root/shell_gc_root"
Oct 28 15:51:44: Started
Oct 28 15:51:44:                 "/home/manny/.cache/lorri/gc_roots/14d16d2f4ecfaaad1d2305ac8b6280b4/gc_root/shell_gc_root"
Oct 28 15:51:44: Started
Oct 28 15:51:45:                 "/home/manny/.cache/lorri/gc_roots/fdf0f8d1169cdb49581245fd32ab921a/gc_root/shell_gc_root"
Oct 28 15:51:45: Started
Oct 28 15:51:45:                 "/home/manny/.cache/lorri/gc_roots/0395f4221b81258ed77b68e21324cddc/gc_root/shell_gc_root"
```

Note that every time a `Started` is logged twice has been a result of `cd`'ing into a new un-watched dir after the initial directory.

**Comment by Shados** [comment]
I've been debugging what I am pretty sure is the same issue independently, and I believe I've found the cause. It's a combination of a few things:
1) [Nix spams `chmod` on some per-user paths on each build](https://github.com/NixOS/nix/blob/629b9b0049363e091b76b7f60a8357d9f94733cc/src/libstore/local-store.cc#L74-L80).
2) [Lorri only filters FS events based on path](https://github.com/target/lorri/blob/34a84caa151833234479b8c5667ba5361bb7d44f/src/watch.rs#L166-L171), without regard to whether or not those events actually constitute an "interesting" change that *should* trigger a rebuild.
3) I think Lorri is queuing up events that occur *during* builds, and then processing/draining them afterward.

The net effect is that if a build is dependent on, say, `/nix/var/nix/profiles/per-user/root`, a single build being triggered will result in multiple `chmod`s being spammed against that very path, which will enter Lorri's event queue, which will sit there until Lorri finishes the build, at which point it will process them and immediately kick off another build in response, which will cause Nix to spam `chmod`s again... repeat ad infinitum.

I'm regularly seeing this happen with only a single lorri instance, watching a single project, and it triggers a fresh `nix-build` **every few seconds** (because the build results are cached, I assume).

**Comment by johnae** [comment]
@Shados That seems to describe my issue quite well. I don't have to switch directory, this starts happening pretty much reliably - it's not difficult to reproduce, rather the opposite. In fact, in my case, so common that I currently don't use lorri.

**Comment by michaelpj** [comment]
This is happening to me too. Seems to be very reproducible.

**Comment by michaelpj** [comment]
It's also `/nix/var/nix/profiles/per-user/root` for me - I don't know why `lorri` thinks it needs to watch that, though.

**Comment by grahamc** [comment]
> It's also /nix/var/nix/profiles/per-user/root for me - I don't know why lorri thinks it needs to watch that, though.

If you're using `<nixpkgs>` and nixpkgs comes from the root user's channel, it watches `/nix/var/nix/profiles/per-user/root` to be able to trigger a new evaluation when your channel updates.

**Comment by michaelpj** [comment]
We don't use `<nixpkgs>`: the `nix-instantiate` call used by `lorri` completes with `NIX_PATH` unset. So I don't know where it's getting that from.

**Comment by michaelpj** [comment]
I found out why it's happening for us!

We use niv, and [this line](https://github.com/nmattia/niv/blob/master/nix/sources.nix#L52) tries to eval `<nixpkgs>`. You still get good behaviour if it fails, which is why I could run things with `NIX_PATH` unset, but presumably this causes lorri to watch it.

Of course, even if you do use nixpkgs, lorri shouldn't loop, so this issue is still valid, but I'll open an issue in niv to fix this.

**Comment by Profpatsch** [comment]
> We use niv, and [this line](https://github.com/nmattia/niv/blob/master/nix/sources.nix#L52) tries to eval `<nixpkgs>`. You still get good behaviour if it fails, which is why I could run things with `NIX_PATH` unset, but presumably this causes lorri to watch it.

Too much magic will kill you. cc @nmattia

**Comment by johnae** [comment]
When trying to solve my issue I tested adding a user channel so that <nixpkgs> would not point to `/nix/var/nix/profiles/per-user/root` and now I don't get these rebuild loops that use up my cpu and drives me crazy. Otoh I don't believe this should be a requirement of lorri.
This "fix" also forces me to upgrade my nixpkgs separately from my NixOS install. That may not be what people want but they'd rather like them to be upgraded together (if you don't have a user channel you default to whatever the system is using).
As @Shados mentions above - it seems to be a chmod call normally that triggers a rebuild which triggers a chmod call which... etc.

**Comment by theotherjimmy** [comment]
This has also been mildly frustrating for me too, as I happen to work on a few projects that are reproducers of this behavior. I think the correct answer is to ignore metadata modification events for paths starting with `/nix/var/nix/profiles/per-user`, as these are the paths that are `chmod`ed unconditionally.

I also noticed that updating an unrelated channel can similarly trigger a build using the same mechanism, as updating the channel link of say `home-manager` will cause nix to re-`chmod` the user's per-user profile directory.

I'll be submitting a patch to change the behavior to what I think is the correct answer shortly.

**Comment by Profpatsch** [comment]
> starting with `/nix/var/nix/profiles/per-user`, as these are the paths that are `chmod`ed unconditionally.

Oh! That’s something lorri itself is doing. We can fix that.

**Comment by theotherjimmy** [comment]
@Profpatsch Could you expand on that? I'm not finding any `set_permissions` calls within the code.

**Comment by theotherjimmy** [comment]
To confirm for myself, I traced this locally, and I think the nix-daemon is doing the chmod:
```
$ sudo bpftrace -e tracepoint:syscalls:sys_enter_chmod { printf("%s: %s\n", comm, str(args->filename)) }

Attaching 1 probe...
nix-daemon: /nix/var/nix/profiles/per-user
nix-daemon: /nix/var/nix/gcroots/per-user
nix-daemon: /nix/var/nix/profiles/per-user/root
nix-daemon: /nix/var/nix/gcroots/per-user/root
nix-daemon: /nix/var/nix/profiles/per-user/jimmy
nix-daemon: /nix/var/nix/gcroots/per-user/jimmy
```

**Comment by theotherjimmy** [comment]
Just ran the same trace without lorri running, and building my reproducer without `--add-root`, and it still does those chmods at the beginning of the `nix build`. This implies that we can't modify lorri to prevent the nix-daemon from calling chmod, unfortunately.

**Comment by Profpatsch** [comment]
Okay, then I misremembered. We only create the per-user gcroots dir when it doesn’t exist already.
