### ISSUE TITLE
Example: get "lorri daemon is not running" after "lorri watch"

### ISSUE THREAD

**Issue by curiousleo** [target/lorri#182]
Expected behaviour: the `direnv` integration works without errors after invoking `lorri watch`. Observed behaviour: `direnv` integration complains that lorri daemon is not running.

Steps to reproduce (on `master` or `rolling-release`):
```
lorri$ nix-build
lorri$ cd example
lorri/example$ ../result/bin/lorri watch
<successfully builds and rebuilds the project as expected on file changes>
```

In another terminal (with `.envrc` changed to point to `../result/bin/lorri`):
```
lorri/example$ # do anything
Info: the lorri daemon is not running. Loading a cached environment.
direnv: export <...>
```

**Comment by Profpatsch** [comment]
> Expected behaviour: the `direnv` integration works without errors after invoking `lorri watch`. Observed behaviour: `direnv` integration complains that lorri daemon is not running.

The message is an Info-level message to tell the user that the daemon is not running, and thus files won’t be evaluated on-the-fly. We can’t figure that out with `lorri watch` … maybe it’s time to either deprecate `lorri watch` or emulate it with the daemon.

Do you think there are any problems with always using the daemon, even for `watch`? It’s as lightweight as `lorri watch`, and communicates over one unix socket file. cc @grahamc

**Comment by curiousleo** [comment]
Thanks @Profpatsch!

It seems to me that the easiest thing to do to prevent other people running into this issue would be to update the [Set up lorri](https://github.com/target/lorri/tree/master/example#set-up-lorri) section of the `example` README to use `lorri daemon` instead of `lorri watch`. I'll see if that works today and put up a PR in case things "just work".

@grahamc told me that `lorri watch` has at least one feature that `lorri daemon` does not currently have, namely the `--once` flag which performs one build and then exits. I'll also look into how that could be ported over to `lorri daemon` so we can get closer to deprecating `lorri watch`.

Does that sound reasonable?

**Comment by Profpatsch** [comment]
> @grahamc told me that `lorri watch` has at least one feature that `lorri daemon` does not currently have, namely the `--once` flag which performs one build and then exits. I'll also look into how that could be ported over to `lorri daemon` so we can get closer to deprecating `lorri watch`.

Hm, I don’t think it makes sense for the daemon to have a `--once` flag. Instead, we would have a command that instructs the daemon to only run one build for a project (the daemon would still continue running).

**Comment by curiousleo** [comment]
https://github.com/target/lorri/pull/190 is my proposal to move `example/README.md` from `lorri watch` to `lorri daemon`.

**Comment by Profpatsch** [comment]
Closing, because I believe the issue was addressed.
