### ISSUE TITLE
Put absolute nix path into lorri binary on compilation

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#197]
I see no good reason why we shouldn’t compile a fixed path to nix into lorri, since we are using nix to build it anyway.

Especially with services, users report errors that stem from a missing nix in the environment. This would fix that problem for everyone.

Disadvantage: Using a different nix requires a recompile with an overwritten `pkgs`, but I don’t think that’s a big problem in practice. We could document it and make it easy to do.

**Comment by flokli** [comment]
I don't think we should do that, this makes using lorri with another custom nix variant harder than it should be.

We should instead show a good error message if nix wasn't found in `$PATH`, and ensure the NixOS module-provided lorri systemd user units already adds the nix from `nix.package` to it.

**Comment by Profpatsch** [comment]
You are right I think.

We are working on generating better error messages when something in the environment is missing, https://github.com/target/lorri/pull/174 was merged and https://github.com/target/lorri/pull/199 adds a specialized exit code for these (as far as the code is aware of them).

**Comment by flokli** [comment]
So this can be closed?
