### ISSUE TITLE
Direnv loads 2 times

### ISSUE THREAD

**Issue by Alkeryn** [target/lorri#200]
So only the first time after running lorri daemon
when you enter a project direnv will load and it will load a second time after any command

it does that double load only once per project and after starting the lorri daemon, which is quite annoying
also seems like the first load don't load new deps, it is like if the first one was just pinging lorri and nothing else

**Comment by Alkeryn** [comment]
![image](https://user-images.githubusercontent.com/11599075/68230275-01951d80-fff9-11e9-84d2-86afa884583c.png)
here is an illustrated example of what  i mean

**Comment by Alkeryn** [comment]
Also sometime it don't reload after editing shell.nix

**Comment by Profpatsch** [comment]
Cannot reproduce on current master.
