### ISSUE TITLE
Lorri dies after being launched with setsid and close terminal

### ISSUE THREAD

**Issue by Alkeryn** [target/lorri#201]
Looks like it dies if it don't have an stdout and tries to output to it idk
i want to run it in background

**Comment by Alkeryn** [comment]
redirecting its output to /dev/null seems to have fixed the issue

**Comment by Profpatsch** [comment]
I’m not sure what the problem here is, what does the error message say, what’s your exact invocation …

**Comment by Alkeryn** [comment]
well there is no error message is launch it using setsid `setsid lorri daemon;exit`
the process just die
tho when doing `setsid lorri daemon &>/dev/null;exit` it works so i believe that it tries to write to stdout and has an error when it don't find a file descriptor maybe idk

**Comment by Profpatsch** [comment]
`setsid` detaches from your current terminal as far as I can see. The process doesn’t die, e.g. try running `lorri -vvv watch`, it will print more output after a few seconds.

**Comment by Alkeryn** [comment]
No what i meant is that when running lorri with setsid and closing it is still alive
but as soon as i enter a project that calls it the lorri process dies !
unless i call it like that `setsid lorri daemon &>/dev/null`
so try doing :
 
`setsid lorri daemon`
close the terminal
pgrep lorri -> it is still alive
enter a direnv directory that call lori
pgrep lorri -> it just died

**Comment by Profpatsch** [comment]
> it just died

Does it output any useful messages? Maybe your terminal doesn’t display stderr because of `setsid`.

**Comment by Alkeryn** [comment]
@Profpatsch well it can't output any message since i close the terminal itself
the point is to have it run in background
setsid don't change the output of a software, i'm running it with setsid and closing the terminal
i'll show you what i mean if that's better

**Comment by Alkeryn** [comment]
1) running setsid
![image](https://user-images.githubusercontent.com/11599075/68498320-da3b8c00-0256-11ea-8bfe-d5dfcbee8f80.png)
2) closing the terminal i ran setsid from
![image](https://user-images.githubusercontent.com/11599075/68498345-e889a800-0256-11ea-8479-08cdab9b5664.png)
3) lorri is still running
![image](https://user-images.githubusercontent.com/11599075/68498358-f3443d00-0256-11ea-8503-e3092cee6ca3.png)
4) as soon as i enter a project it dies
![image](https://user-images.githubusercontent.com/11599075/68498395-ffc89580-0256-11ea-8c0d-cb7388e7e3f0.png)

this behavior don't happen when i run it with `setsid lorri daemon &>/dev/null`
i think the issue is the file descriptor not existing anymore upon closing the terminal so lorri exiting with error when it tries to output to stdout

by using &>/dev/null it change its file descriptor to /dev/null so it still has a file descriptor once the terminal is closed even tho that is /dev/null

**Comment by Profpatsch** [comment]
> i think the issue is the file descriptor not existing anymore upon closing the terminal so lorri exiting with error when it tries to output to stdout

Do you think that is bug in lorri? I’m not sure how we would check every time we print something to stdout. This is more of a rust standard library thing it looks like.
