### ISSUE TITLE
`lorri ping_` doesn’t trigger reevaluation if the daemon watches the nix file already

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#212]
I noticed that if I run `lorri direnv` (via the direnv integration), the daemon sometimes does not start a build.

More specifically, if I remove the `shell_gc_root` (which the daemon prints in its `Started` messages), the environment won’t be rebuild if I run `lorri ping_ /path/to/shell.nix`, as long as the daemon is still running. If I restart the daemon, it is rebuilt after `ping_`.

The ping is received by the daemon here:

https://github.com/target/lorri/blob/a0ff0a51f742f1e73f4adefd0d46c67c6032016c/src/ops/daemon.rs#L42-L44
it is written to `accept_messages_tx` and read from the reading end further down:

https://github.com/target/lorri/blob/a0ff0a51f742f1e73f4adefd0d46c67c6032016c/src/ops/daemon.rs#L60-L74

The problem lies in `daemon.add()`, which has a different semantics than what I thought when writing this code:

https://github.com/target/lorri/blob/a0ff0a51f742f1e73f4adefd0d46c67c6032016c/src/daemon.rs#L64-L80

It adds projects to the daemon, but only if the project was not added yet (`or_insert_with`).

Instead, we need to be able to influence the `build_loop`s somehow, which are running inside threads. I propose to add a channel going from the daemon to each `build_loop`s and extending the hash map by the `tx` going to each builder:

https://github.com/target/lorri/blob/a0ff0a51f742f1e73f4adefd0d46c67c6032016c/src/daemon.rs#L29-L31

Then we can forward a message to the build_loop that a build should be queried, even if no file has changed in the meantime.

**Comment by curiousleo** [comment]
I've started looking at this here: https://github.com/target/lorri/compare/master...curiousleo:ping-trigger-eval?expand=1

**Comment by curiousleo** [comment]
Repro:

#### 1. Start daemon
```console
# terminal 1
$ cargo run -- daemon
lorri: ready
```

#### 2. First ping
```console
# terminal 2
$ cargo run -- ping_ $(readlink -f shell.nix)
```

#### 3. Check: daemon builds
```console
# terminal 1
[...]
Started(
    ProjectAdded(
        NixFile(
            "/home/leo/Code/lorri/shell.nix",
        ),
    ),
)
Completed(
    BuildResults {
        output_paths: OutputPaths {
            shell_gc_root: RootPath(
                "/home/leo/.cache/lorri/gc_roots/2043910c8519bf079838568f54a73839/gc_root/shell_gc_root",
            ),
        },
    },
)
```

#### 4. Remove `gc_root` and ping again
```
# terminal 2
$ rm /home/leo/.cache/lorri/gc_roots/2043910c8519bf079838568f54a73839/gc_root/shell_gc_root
$ cargo run -- ping_ $(readlink -f shell.nix)
```

#### 5. Bug: daemon should trigger build, but doesn't
```console
# terminal 1
[nothing happens]
```

**Comment by grahamc** [comment]
I think this means we should watch the GC root directory as well, and trigger a new evaluation if the GC root is touched. We shouldn't trigger a new eval every time the direnv hook is executed.

**Comment by curiousleo** [comment]
> I think this means we should watch the GC root directory as well, and trigger a new evaluation if the GC root is touched. We shouldn't trigger a new eval every time the direnv hook is executed.

The problem with a naive implementation of this is that it will send `lorri` into an infinite rebuild loop: the GC root is touched as a result of rebuilding, which triggers a rebuild, etc.

We could probably get 99% of the way there by only watching the GC root while `lorri` is _not_ in the process of rebuilding the project. That would still leave open the possibility of someone removing the GC root between "build finishes" and "GC root added to notify watchlist", but you'd probably have to try very hard to accomplish that.
