### ISSUE TITLE
Include version in error reports for easier triage

### ISSUE THREAD

**Issue by curiousleo** [target/lorri#219]
Now that `lorri` is on nixpkgs (https://github.com/NixOS/nixpkgs/pull/72889), people can download and run it from there and we may get bug reports this way.

To be able to pinpoint the version of `lorri` that had the bug, we should include a version in the error messages.

One way of setting a version would be to change `Cargo.toml` in the build process in the nixpkgs package declaration. I'm sure there are other ways too. And then we need to make sure that the version string is actually included in error messages.

Outcome:
- From looking at an error message reported by users who got `lorri` from nixpkgs, we can easily infer which commit that version of `lorri` was built from.

**Comment by curiousleo** [comment]
There already is some infrastructure set up for version numbers:

<pre>$ git grep BUILD_REV_COUNT
build.rs<font color="#06989A">:</font>    println!(&quot;cargo:rerun-if-env-changed=<font color="#CC0000"><b>BUILD_REV_COUNT</b></font>&quot;);
build.rs<font color="#06989A">:</font>    let rev_count = env::var(&quot;<font color="#CC0000"><b>BUILD_REV_COUNT</b></font>&quot;)
build.rs<font color="#06989A">:</font>        .expect(&quot;<font color="#CC0000"><b>BUILD_REV_COUNT</b></font> not set, please reload nix-shell&quot;)
build.rs<font color="#06989A">:</font>        .expect(&quot;<font color="#CC0000"><b>BUILD_REV_COUNT</b></font> should be parsable as usize&quot;);
default.nix<font color="#06989A">:</font>      <font color="#CC0000"><b>BUILD_REV_COUNT</b></font> = src.revCount or 1;
shell.nix<font color="#06989A">:</font>  <font color="#CC0000"><b>BUILD_REV_COUNT</b></font> = 1;
shell.nix<font color="#06989A">:</font>    inherit <font color="#CC0000"><b>BUILD_REV_COUNT</b></font> RUN_TIME_CLOSURE;
</pre>

At the top-level, `BUILD_REV_COUNT` for nixpkgs releases is set here: https://github.com/NixOS/nixpkgs/blob/7fafd45ad758fcb3d24b1da38039c4e73d5d8902/pkgs/tools/misc/lorri/default.nix#L37.

```nix
{ #...
  BUILD_REV_COUNT = src.revCount or 1;
}
```

Explanation: https://github.com/target/lorri/blob/c315a4357c0cea91be280fbe68042bc0a0367560/default.nix#L14-L19

The problem is that the nixpkgs `default.nix` uses `fetchFromGitHub` (https://github.com/NixOS/nixpkgs/blob/7fafd45ad758fcb3d24b1da38039c4e73d5d8902/pkgs/tools/misc/lorri/default.nix#L26), which internally uses `fetchzip` (https://github.com/NixOS/nixpkgs/blob/7fafd45ad758fcb3d24b1da38039c4e73d5d8902/pkgs/build-support/fetchgithub/default.nix#L14), which does not appear to set "revCount".

I see the following options:
- Use `fetchGit` instead of `fetchFromGitHub` to get `revCount`
- Patch `fetchFromGitHub` to set `revCount`
- Use `rev` instead of `revCount` in the version string.

**Comment by curiousleo** [comment]
With

```diff
-  src = fetchFromGitHub {
-    owner = "target";
-    repo = pname;
+  src = builtins.fetchGit {
+    url = "https://github.com/target/lorri.git";
+    name = pname;
     # Run `eval $(nix-build -A lorri.updater)` after updating the revision!
     rev = "03f10395943449b1fc5026d3386ab8c94c520ee3";
-    sha256 = "0fcl79ndaziwd8d74mk1lsijz34p2inn64b4b4am3wsyk184brzq";
   };
```

I get 

```console
$ nix-build . -A lorri --show-trace
fatal: not a tree object: 03f10395943449b1fc5026d3386ab8c94c520ee3
error: while evaluating the attribute 'BUILD_REV_COUNT' of the derivation 'lorri-unstable-2019-10-30' at /home/leo/Code/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:191:11:
program 'git' failed with exit code 128
```

Even though the commit exists: https://github.com/target/lorri/commit/03f10395943449b1fc5026d3386ab8c94c520ee3

**Comment by curiousleo** [comment]
Option (C) won't work just like that either because the `upgrade` command assumes `VERSION_BUILD_REV` to be a number that can be compared with changelog entry versions.

**Comment by curiousleo** [comment]
https://github.com/NixOS/nixpkgs/pull/77198 uses another approach (D): now the `updater` script determines the rev count and patches the nix file.

**Comment by curiousleo** [comment]
Somewhat related: https://github.com/target/lorri/issues/219

**Comment by Profpatsch** [comment]
What happened to this? I think we are asking people to submit `lorri info` output, which includes the version number.

**Comment by curiousleo** [comment]
I think this can be closed: released version now have `MAJOR.MINOR` in the `lorri info` output.
