### ISSUE TITLE
Pull clippy from stable rust (removes need for nightly rust)

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#220]
Clippy is compatible with recent stable releases too: https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md. In fact, according to the README, clippy may _not_ be compatible with every nightly version. We can get rid of `rustChannels`, I think, if the only reason we have it is to be able to run `clippy`.

I just realised that two lines later we use `rustChannels.stable.rust`. But `clippy` is also available via `nixpkgs.rustPackages.clippy` - no extra channels needed!

_Originally posted by @curiousleo in https://github.com/target/lorri/pull/206_

**Comment by curiousleo** [comment]
Actually I think I misread this - nightly Rust is passed on to `nix/racer.nix`, and racer [still needs Rust nightly](https://github.com/racer-rust/racer#installation). I think this ticket should be closed until that's no longer the case.

**Comment by Profpatsch** [comment]
But we can pull clippy from stable rust instead, right?

**Comment by curiousleo** [comment]
> But we can pull clippy from stable rust instead, right?

Turns out we already are - see #246.
