### ISSUE TITLE
lorri overwrites PATH instead of prepending

### ISSUE THREAD

**Issue by bergey** [target/lorri#223]
Trying out `lorri` today, I was surprised to find that it overwrites PATH.  Is this intended behavior?  This breaks my access to a bunch of commands that I don't include in my `shell.nix`, but use frequently (`rg`, `jq`, `git`, `psql`).  It also means I can't run `lorri daemon` from the project directory.

I'm using NixOS, and testing today on a Haskell project: https://github.com/bergey/crispy-broccoli
If this is not intended behavior, and it's not happening for others, I'm happy to debug some more what might be different about my setup.

**Comment by Profpatsch** [comment]
It doesn’t overwrite PATH:

https://github.com/target/lorri/blob/master/src/ops/direnv/envrc.bash#L132

Can you give some more information? Which version of lorri do you use? What did you try, what effect was there?

**Comment by bergey** [comment]
Thank you for confirming that this is not intended behavior.  I saw the line you quote in the output of `lorri direnv` and was puzzled.

`lorri --version` reports `lorri 0.1.0`.  `direnv-2.20.1` from nixpkgs.  I installed lorri by running `$ nix-env -if https://github.com/target/lorri/archive/rolling-release.tar.gz` sometime this past Friday, per the README.

I previously have used `nix-shell` directly, and with direnv `use_nix`.  I just confirmed with `diff` that `use_nix` produces the same `PATH` as `nix-shell`.  After running `lorri daemon` in one terminal & `direnv allow` in another, `cd` into the working directory changes PATH to one that is similar, but missing all of my global path.  Both are here: https://gist.github.com/bergey/d7908ce0fada627be49e9b256e852901

I'll try using `mkShell` in my `shell.nix` instead of `mkDerivation`, and checking if the example project works as expected.  Let me know if you have other suggestions for debugging.

**Comment by bergey** [comment]
I tracked this down to a trailing `"` character in my `PATH`, which certainly doesn't belong there.  I think lorri is doing fine here.  More details in case anyone else runs into the same situation:

When entering the working directory, direnv prints the error:

```
./.envrc: eval: line 64: unexpected EOF while looking for matching `"'
./.envrc: eval: line 65: syntax error: unexpected end of file
```

line 64 (of the output of `lorri direnv`) reads: `eval "$varname=${!varname}${original:+${separator}${original}}"`

The quote character in `PATH` causes this line not to run, leaving `PATH` set to the `nix-shell` paths, without `$original` appended.
