### ISSUE TITLE
Show journal logs on a single line

### ISSUE THREAD

**Issue by flokli** [target/lorri#224]
Currently lorri logs 10 different log lines during a `lorri direnv` dumping some structure.

When using the NixOS module, logs are collected via the per-user journal.

Showing these logs now looks a bit odd:

```
Nov 15 16:50:20 xps lorri[27661]: Started
Nov 15 16:50:23 xps lorri[27661]: Completed(
Nov 15 16:50:23 xps lorri[27661]:     BuildResults {
Nov 15 16:50:23 xps lorri[27661]:         output_paths: OutputPaths {
Nov 15 16:50:23 xps lorri[27661]:             shell_gc_root: RootPath(
Nov 15 16:50:23 xps lorri[27661]:                 "/home/flokli/.cache/lorri/gc_roots/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/gc_root/shell_gc_root",
Nov 15 16:50:23 xps lorri[27661]:             ),
Nov 15 16:50:23 xps lorri[27661]:         },
Nov 15 16:50:23 xps lorri[27661]:     },
Nov 15 16:50:23 xps lorri[27661]: )
```

Can we just log JSON, and not pretty print it, at least when logging to the journal?

**Comment by Profpatsch** [comment]
> Can we just log JSON, and not pretty print it, at least when logging to the journal?

Are journal logs expected to be on one line?

We haven’t given logging output any thoughts so far.

**Comment by flokli** [comment]
Individual events should be one single log line entry, this makes parsing log entries wayy easier Encoding as JSON, and submitting via `syslog(3)` is one way to handle multi-line output in a single log entry.

I recommend reading http://0pointer.de/blog/projects/journal-submit.html. On top of the regular `syslog(3)` route, it also explains how to annotate log lines with structured data, by using `sd_journal_send`. However, this would require linking to `libsystemd`, and not sure about rust's support for that, and we probably want to use the same logger for MacOS, too.

**Comment by grahamc** [comment]
It'd be good to look in to switching to https://github.com/slog-rs/slog, which supports structured logging with lots of types of backends including journald: https://crates.io/crates/slog-journald

This Started/Completed output is a bare minimal example of what the output, just enough to show it is working. In fact I don't think this is even using a logger: I think it is just a `println!()`. Improving it would be good.

**Comment by flokli** [comment]
Yeah, this sounds like a good plan. I also don't think the current output is what we should log :-)

**Comment by Profpatsch** [comment]
> I also don't think the current output is what we should log :-)

yeah, we’re gonna have a better interface once https://github.com/target/lorri/pull/183 is in.
