### ISSUE TITLE
example: add a section for setting up the daemon as a service

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#226]
After finishing the tutorial, the next step the user likely wants to do is set up the daemon in a more permanent/integrated fashion.

Follow-up to https://github.com/target/lorri/pull/191

**Comment by curiousleo** [comment]
https://github.com/target/lorri/blob/master/contrib/README.md was created to address this question. What do you think is missing there?

**Comment by Profpatsch** [comment]
Great, I think we can close this with https://github.com/target/lorri/pull/233
