### ISSUE TITLE
Add Github issue template

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#239]
Since we have the daemon and various service providers now (nixos, home-manager, the macos thing…), plus multiple ways to install lorri (self-upgrade, nixpkgs), we should require a bunch of information from users when they open an issue (as easy to get as possible).

We have `lorri info`, so we should add as much diagnostic information as possible to that (so users just have to copy & paste).

**Comment by curiousleo** [comment]
I think it would be good to have the following:

- An issue template for bug reports
- An issue template for feature requests
- A `CONTRIBUTING.md` explaining how to develop lorri
- A PR template which points people to the `CONTRIBUTING.md` and provides a simple skeleton for PR descriptions.

**Comment by curiousleo** [comment]
https://github.com/NixOS/nixpkgs/pull/64983 is a good example of having multiple issue templates.
