### ISSUE TITLE
syntax error in lorri-keep-env-hack-nix-shell.drv

### ISSUE THREAD

**Issue by srstrong** [target/lorri#248]
Hi,

I'm very new to lorri / nix, so apologies if this is just something I've missed.  I've got a relatively clean nix / loris setup on macOS 10.15.1.  The nix side of things appears to be working as expected, but I'm having problems on the lorri side.  I've got a terminal running ```lorri daemon``` and then in another tab moved into a directory that has a default .envrc and shell.nix (as created with ```lorri init```).  In the daemon window, lorri detects the entry into the directory and starts evaluating, but finally fails with:

```
            "instantiated \'hello-2.10.tar.gz\' -> \'/nix/store/7lybxkl8ysgddl2pw0gkimfr1ln13g23-hello-2.10.tar.gz.drv\'",
            "instantiated \'hello-2.10\' -> \'/nix/store/xfc63dkn9jqzqq81jzs1mryjrrs5xch4-hello-2.10.drv\'",
            "evaluating file \'/nix/store/hnlka8mzx0h56yn9l8yi009i7a2w69ym-closure.nix\'",
            "instantiated \'lorri-keep-env-hack-nix-shell\' -> \'/nix/store/bmjsfcd1vnyjdcf4nvgiwcgnn7wmgz7p-lorri-keep-env-hack-nix-shell.drv\'",
            "error: syntax error, unexpected \',\', expecting \')\', at /nix/store/bmjsfcd1vnyjdcf4nvgiwcgnn7wmgz7p-lorri-keep-env-hack-nix-shell.drv:1:15",
        ],
    },
)
```

I've seen one issue raised a couple of months ago that looks very similar, but I think I'm on versions that claim to have fixes.  Versions I'm running are:

lorri 0.1.0
nix (Nix) 2.4pre7044_2989c0f

any help would be much appreciated

**Comment by curiousleo** [comment]
Hi @srstrong, as far as I can tell, the syntax error here appears not to be in the nix file, but in the derivation file generated by nix itself.

Could you attach `/nix/store/bmjsfcd1vnyjdcf4nvgiwcgnn7wmgz7p-lorri-keep-env-hack-nix-shell.drv` to this issue please?

**Comment by philipstears** [comment]
Hi. I had the exact same issue - after doing a bit of investigation, I wonder if the problem is this commit to nix:

https://github.com/NixOS/nix/commit/12913ccf454c1bc82a51c59872f8185b40c533c5

Coupled with the "current" approach to getting nix working on Catalina - which has been to symlink `/nix` to `/usr/local/nix`.

If I'm understanding correctly, that would mean that the code in the above commit would canonicalize the path from `/nix/store/bmjsfcd1vnyjdcf4nvgiwcgnn7wmgz7p-lorri-keep-env-hack-nix-shell.drv` to `/usr/local/nix/store/bmjsfcd1vnyjdcf4nvgiwcgnn7wmgz7p-lorri-keep-env-hack-nix-shell.drv`, and then check to see if it is a patch in the store - which will fail, because nix thinks the store is at `/nix`.

**Comment by srstrong** [comment]
File attached (renamed to .dev.txt to keep GitHub happy).  But I suspect @philipstears is onto the real issue...

[bmjsfcd1vnyjdcf4nvgiwcgnn7wmgz7p-lorri-keep-env-hack-nix-shell.drv.txt](https://github.com/target/lorri/files/3910203/bmjsfcd1vnyjdcf4nvgiwcgnn7wmgz7p-lorri-keep-env-hack-nix-shell.drv.txt)

**Comment by philipstears** [comment]
I just ran an experiment - creating a new APFS volume for nix, mounting it via `/etc/fstab`, and updating `/etc/synthetic.com` to create the mount directory - and now lorri is working fine for me. So it really is looking like an issue with symlinking the store.

**Comment by curiousleo** [comment]
> I just ran an experiment - creating a new APFS volume for nix, mounting it via `/etc/fstab`, and updating `/etc/synthetic.com` to create the mount directory - and now lorri is working fine for me. So it really is looking like an issue with symlinking the store.

Thanks for looking into this! I don't have too much context on Nix issues on Catalina - do you know if this is a known issue? If not, could you open an issue upstream?

**Comment by philipstears** [comment]
No worries , there's nothing like a bit of motivated self-interest :)

I've added some comments to https://github.com/NixOS/nix/issues/2925 where there's an on-going conversation about Catalina support in general. Let's see what folks say!

**Comment by curiousleo** [comment]
> Hi. I had the exact same issue - after doing a bit of investigation, I wonder if the problem is this commit to nix: [...]

Looking at this again, I wonder: @philipstears, when you said you had the exact same issue: did you get a _syntax error_ as well? Naively I would think that the symlink issue you're describing would not manifest itself as a syntax error in this way. But it could be that Nix' error reporting is just very misleading here.

On the other hand, I can see nothing wrong with the `.drv` file @srstrong posted. I think that the comma Nix is complaining about is perfectly acceptable where it is.

**Comment by philipstears** [comment]
I do indeed get a syntax error. 

My understanding is that's because the `.drv` file is outside of the store as far as nix is concerned, and thus being treated as if it were a nix file rather than a derivation file.

**Comment by curiousleo** [comment]
> I do indeed get a syntax error.
> 
> My understanding is that's because the `.drv` file is outside of the store as far as nix is concerned, and thus being treated as if it were a nix file rather than a derivation file.

Ah wow, thanks for confirming.

**Comment by curiousleo** [comment]
I don't see what we can do on the lorri side here. I've created https://github.com/target/lorri/issues/248 as a tracking issue for the Nix <> Catalina incompatibility issue.
