### ISSUE TITLE
Nixpkgs systemd unit's explicit path does not contain git

### ISSUE THREAD

**Issue by IvanMalison** [target/lorri#255]
Many of my nix builds seem to be failing with:

```
Dec 10 13:19:07 ivanm-dfinity-razer lorri[1797]:             "error: executing \'git\': No such file or directory",
Dec 10 13:19:07 ivanm-dfinity-razer lorri[1797]:             "error: program \'git\' failed with exit code 1",
Dec 10 13:19:07 ivanm-dfinity-razer lorri[1797]:             "(use \'--show-trace\' to show detailed location information)",
```

I haven't looked in to it too deeply, but my guess is that this has something to do with the way the runtime-closure is set up. I'm assuming that what I need to do is add git to the paths that are set as part of the "lorri-runtime-tools", but I'm wondering why this isn't done by default.

**Comment by IvanMalison** [comment]
Even if this isn't done by default, it seems like runtime.nix should provide an easy way to add additional things that may be needed as runtime dependencies by lorri.

**Comment by curiousleo** [comment]
Hi @IvanMalison, would you be able to share an (ideally minimal) repro `shell.nix`?

**Comment by IvanMalison** [comment]
My guess at the cause of this issue was incorrect. This actually has to do with the way the systemd unit is configured in nixpkgs, where the path is explicitly set to:

https://github.com/nixos/nixpkgs/blob/6b73d29775213361370f003fa4476bcf94572c28/nixos/modules/services/development/lorri.nix#L35
```
      path = with pkgs; [ config.nix.package gnutar gzip ];
```

on my machine, this yields:
```
Environment="PATH=/nix/store/sm740vh74gh7r8ww6q3wf067xkq1nb64-nix-2.3.1/bin:/nix/store/gpd7dd7i1jqcwr1wiszcxypjqk61nimc-gnutar-1.32/bin:/nix/store/xn2bim352zk1xv0s8vzqg6zc1znj7nl0-gzip-1.10/bin:/nix/store/j0lhk5xkky410h5v9af98sz6kd8cbp40-coreutils-8.31/bin:/nix/store/kmc865qs56czqk5k5vr0nj4zvfijlq7n-findutils-4.7.0/bin:/nix/store/20b535jb98hy7k4z8vkrlkjma212a3l5-gnugrep-3.3/bin:/nix/store/dv52knazq6pb1zv9pazzj666zg550zni-gnused-4.7/bin:/nix/store/qjnhav18gi6ry63cbkni4fh36kq13v32-systemd-243/bin:/nix/store/sm740vh74gh7r8ww6q3wf067xkq1nb64-nix-2.3.1/sbin:/nix/store/gpd7dd7i1jqcwr1wiszcxypjqk61nimc-gnutar-1.32/sbin:/nix/store/xn2bim352zk1xv0s8vzqg6zc1znj7nl0-gzip-1.10/sbin:/nix/store/j0lhk5xkky410h5v9af98sz6kd8cbp40-coreutils-8.31/sbin:/nix/store/kmc865qs56czqk5k5vr0nj4zvfijlq7n-findutils-4.7.0/sbin:/nix/store/20b535jb98hy7k4z8vkrlkjma212a3l5-gnugrep-3.3/sbin:/nix/store/dv52knazq6pb1zv9pazzj666zg550zni-gnused-4.7/sbin:/nix/store/qjnhav18gi6ry63cbkni4fh36kq13v32-systemd-243/sbin"
```

and so it is no wonder that git is not accessible from lorri.

It looks like you @curiousleo are responsible for this configuration, so I'm wondering why lorri needs to be set up with an explicit path in this way.

**Comment by IvanMalison** [comment]
Perhaps this issue should be moved to nixpkgs?

**Comment by IvanMalison** [comment]
@curiousleo As for a repro, anything that needs to fetch something using git seems to have this issue for me.

**Comment by curiousleo** [comment]
> @curiousleo As for a repro, anything that needs to fetch something using git seems to have this issue for me.

Could you share a snippet of how your `shell.nix` is calling `git`?

**Comment by philipstears** [comment]
I'm also getting this under NixOS when a package needs to go and fetch something from git, for example:

```
let
  erlangReleases = builtins.fetchTarball https://github.com/nixerl/nixpkgs-nixerl/archive/v1.0.2-devel.tar.gz;

  nixpkgs =
    import <nixpkgs> {
      overlays = [
        (import erlangReleases)
      ];
    };

in

with nixpkgs;

mkShell {
  buildInputs = with pkgs; [
    nixerl.erlang-22-1-8.erlang
  ];
}
```

nixerl is an overlay I created to make various Erlang releases available, it just calls override on the standard nixpkgs derivations with specific version numbers - that triggers downloading the source because the package isn't in the standard binary cache.

I'm having to run `lorri daemon` interactively at the moment to work around this issue.

**Comment by curiousleo** [comment]
Thanks for the repro shell @philipstears! Yes that looks like a packaging issue. I'll follow up on this

**Comment by curiousleo** [comment]
It is a little odd that `builtins.fetchTarball` calls `git` in the background - naively, it should just HTTP request the file and then unzip + untar it? But this demonstrates that Nix itself calls out to a `git` binary (rather than having a built-in git library, for example), so it shows the problem. Thanks!

**Comment by philipstears** [comment]
That `fetchTarball` succeeds, it just brings down the overlay - ultimately it's the `nixerl.erlang-22-1-8.erlang` evaluation that will fail, which via a slightly circuitous route, ends up calling https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/erlang/generic-builder.nix#L13

**Comment by curiousleo** [comment]
The `nixpkgs` PRs have been merged. I think that should fix the issue. Thanks for the reports!
