### ISSUE TITLE
On darwin, daemon running but not watching or responding to anything

### ISSUE THREAD

**Issue by Ptival** [target/lorri#263]
I'm encountering issues setting up the daemon on darwin. At first I though it was my setup as a service that was causing issues, but it seems that even running the daemon manually causes trouble.

When I run:
```
RUST_LOG=lorri=debug RUST_BACKTRACE=1 /nix/store/#{...}-lorri/bin/lorri -vvv daemon
```
All I see as output is:
```
Dec 25 09:51:32.227 INFO ready, lorri_version: 1
```

While the daemon appears to be running, no amount of calling `lorri init` or `lorri ping_ ./shell.nix` elsewhere seems to trigger any interaction with it.

I have no idea whether it's waiting and just not receiving my requests, or blocked on something. Is there any way to debug this further?

Thanks!

**Comment by Ptival** [comment]
Investigating this. I have clone a copy of the repository, and built, and ran the daemon from there. This works perfectly.

Somehow the daemon that I got installed via the MacOS darwin-installer tutorial is causing trouble.

**Comment by Ptival** [comment]
Ah, I think I resolved it.

Turns out I had an old version of `lorri` installed in my user's nix-env, which seemed to not be doing the right thing for `ping_`. Uninstalling it made everything work.

**Comment by curiousleo** [comment]
Thanks for documenting your issue here, this may be useful to others.
