### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by curiousleo** [target/lorri#269]
https://github.com/target/lorri/blob/master/MAINTAINERS.md#cutting-a-release says:
> TODO

That section should be updated, **answering the following questions:**
- [x] Q: What is the relationship between `master` and `rolling-release`?
  A: `rolling-release` is no longer used; releases are made from `master`.
- [x] Q: How is the version number determined?
  A: we use both revCount and [this versioning scheme documented in MAINTAINERS.md](https://github.com/target/lorri/blob/master/MAINTAINERS.md#versioning-scheme)
- [x] Q: Which distribution channels are supported (currently `nixos-unstable` and `nixos-19.09`)?
  A: `nixos-stable` and `nixos-19.09` are the supported distribution channels.
- [ ] Q: For each channel, what is our update policy (under which circumstances do we update the channel)?
- [x] Q: For each channel, how do we actually release the new lorri version?
  A: See [MAINTAINERS.md](https://github.com/target/lorri/blob/master/MAINTAINERS.md#publishing-a-release-on-nixpkgs)

As an example, lorri `master` may at some point require Rust 1.39 which is not (at this moment) included in `nixos-19.09`, so the `nixos-19.09` update policy may be "backport critical bugfixes" whereas the `nixos-unstable` update policy may be "update every month or so".

**Comment by curiousleo** [comment]
@Profpatsch perhaps you can answer the first question, "What is the relationship between `master` and `rolling-release`" and how `rolling-release` is updated?

![Screenshot from 2020-01-07 13-26-06](https://user-images.githubusercontent.com/697092/71895446-63851700-3151-11ea-9bdc-dbe371912d90.png)

That's something I really don't understand at the moment.

**Comment by Profpatsch** [comment]
> lorri `master` now requires Rust 1.39

Huh, why is that?

> so the `nixos-19.09` update policy may be "backport critical bugfixes" whereas the `nixos-unstable` update policy may be "update every month or so".

That’s the reason we originally didn’t want to put it into nixpkgs, since it’s going to be a considerable maintenance overhead (people opening issues about already fixed bugs, necessary backporting, …).

**Comment by curiousleo** [comment]
> > lorri `master` now requires Rust 1.39
> 
> Huh, why is that?

`lorri services` uses async/await to simplify the implementation of the service manager, and Rust 1.39 is the first stable Rust release to support async/await: https://blog.rust-lang.org/2019/11/07/Rust-1.39.0.html#the-await-is-over,-async-fns-are-here

**Comment by curiousleo** [comment]
Thanks for offering to document the current release process @Profpatsch! I'm happy to help where I can.

Chatting with @grahamc, we came up with this plan for how this could work in the future. In particular, we're trying to address the issue of versioning so there is no need for ugly hacks as in this (rejected) PR: https://github.com/NixOS/nixpkgs/pull/77198/files#diff-cf738915a62799c87e7c6834f40c3fcdR61-R71

Releases should have Git tags corresponding to their version number (rev count).

We would like a nix file (perhaps `release.nix` can be used for this) which
- determines the current version
- creates a tarball with the lorri sources as well as a VERSION file which contains the version

This tarball should then be uploaded to Github and attached to the relevant tag as a "release".

`build.rs` should be changed such that it reads the VERSION file if it exists (whether it should have priority over the BUILD_REV_COUNT environment variable is to be determined) and compiles it into the binary as lorri's version.

Finally, the package description nix file in `nixpkgs` should just download the source tarball and build it. It should not need to set the version via BUILD_REV_COUNT or any other way, since the version is already contained in the tarball.

**Comment by Profpatsch** [comment]
I think the current process is really easy to describe: `rolling-release` is master whenever we decide it’s stable enough. The current `rolling-release` branch has a few commits because those were rebased onto master after adding the tag to rolling-release.

**Comment by curiousleo** [comment]
The release for https://github.com/target/lorri/issues/272 is being done from `master`. Once that has gone through, I think we can get rid of the `rolling-release` branch and just make it a rule that we release from `master` instead of `rolling-release`.

**Comment by grahamc** [comment]
I think we should keep the branch but not update it. There are docs that point to it (even old ones) and it doesn't cost anything to keep it. It is a bit weird to have a stale "rolling-release" branch but oh well. We could update the README on that branch to say it is no longer updated.

**Comment by curiousleo** [comment]
Somewhere we should probably state that there is no point in putting lorri on crates.io in its current form. The build process fundamentally requires Nix. I think that if we do a 1.0 release, people may want to package lorri and will ask why it is not on crates.io like every other Rust CLI tool.

**Comment by curiousleo** [comment]
Thoughts on "how is the release version determined":
- The release notes are currently numbered by commit count. This is unusual: users are probably more used to x.y.z version schemes than something like "version 450" (which would be the release number for HEAD right now).
- In a version scheme like x.y.z, there is meaning attached to which of x, y or z gets incremented when a new version is released. We could adopt semantic versioning here, in which case we would need to defined precisely what "incompatible change" means for lorri in terms of subcommands, arguments, outputs and behaviour.

**Comment by curiousleo** [comment]
> For each channel, how do we actually release a new version?

Starting points for this are:
- lorri lives in `pkgs/tools/misc/lorri` in nixpkgs: https://github.com/NixOS/nixpkgs/tree/master/pkgs/tools/misc/lorri
- lorri tests live in `nixos/tests/lorri`: https://github.com/NixOS/nixpkgs/tree/master/nixos/tests/lorri
- the nixpkgs backporting procedure is documented here: https://github.com/NixOS/nixpkgs/blob/d6a98987717b31e2d89b267608ea6c90bd5eea56/.github/CONTRIBUTING.md#backporting-changes

**Comment by curiousleo** [comment]
The remaining open question is
> For each channel, what is our update policy (under which circumstances do we update the channel)?

I think this depends on the speed of development from this point on. It would be nice to have some regularity. And since lorri is meant to be a somewhat experimental tool for power-users, I think that making releases in relatively short intervals is a good idea.
