### ISSUE TITLE
Release fix for #176 to nixpkgs

### ISSUE THREAD

**Issue by curiousleo** [target/lorri#272]
https://github.com/target/lorri/issues/176 is bugging many users. It has been fixed in https://github.com/target/lorri/pull/260. The plan is to release 7b84837b9988d121dd72178e81afd440288106c5 as `unstable-2020-01-09`.

- [x] Create PR against nixpkgs `master` with new version: https://github.com/NixOS/nixpkgs/pull/77380
- [x] Merge PR against nixpkgs `master` with new version
- [x] Create PR against nixpkgs `nixos-19.09` with new version: https://github.com/NixOS/nixpkgs/pull/77432
- [x] Merge PR against nixpkgs `nixos-19.09` with new version

**Comment by curiousleo** [comment]
`rolling-release` still depends on `notify-4.0.6`, but #260 uses `ModifyKind` from `notify-5.0.0.pre-1`. So just cherry-picking the commit from #260 won't work.

- https://docs.rs/notify/4.0.6/notify/?search=modifykind
- https://docs.rs/notify/5.0.0-pre.1/notify/event/enum.ModifyKind.html

The `notify` dependency was upgraded here: https://github.com/target/lorri/pull/217.
#260 uses `slog` too, which was introduced in https://github.com/target/lorri/pull/243.

I see three options:
- We backport the change from #260 to `rolling-release` using notify v4 instead of v5 API and env_logger instead of slog
- We attempt to cherry-pick #217 (and possibly #243) and then #260
- We release a new version of lorri from some `master` commit that includes #260

**Comment by curiousleo** [comment]
Expanding on (C) a bit: #260 was merged into `master` in commit 7ff97e14e8ecbd84a8c35ed8cb2885691a827d7a. The changes to `master` since then have been completely innocent: 7ff97e14e8ecbd84a8c35ed8cb2885691a827d7a...7b84837b9988d121dd72178e81afd440288106c5, so releasing from current `master` is no more "dangerous" than releasing from 7ff97e14e8ecbd84a8c35ed8cb2885691a827d7a.

**Comment by curiousleo** [comment]
Looking at the diff between the version released on nixpkgs and `master`: 03f10395943449b1fc5026d3386ab8c94c520ee3...7b84837b9988d121dd72178e81afd440288106c5
- https://github.com/target/lorri/pull/221, https://github.com/target/lorri/pull/253 and https://github.com/target/lorri/pull/257 are the biggest changes
- https://github.com/target/lorri/pull/254 may be a deal-breaker for `nixos-19.09`, which does not ship Rust 1.39. I'll need to check.

**Comment by curiousleo** [comment]
Actually, `master` builds on `nixos-19.09` despite #254 (`nixos-19.09` is on Rust 1.37). That PR is a misnomer: it just uses the Rust version in nixpkgs. That version happens to be 1.40 on nixpkgs `master` / `nixos-unstable`, and 1.37 on `nixos-19.09`. Since lorri `master` does not currently use features that require anything above Rust 1.37, we can release lorri from `master` as-is to `nixos-19.09`.

**Comment by Profpatsch** [comment]
Then let’s just use master and backport to 19.09.

**Comment by curiousleo** [comment]
https://github.com/NixOS/nixpkgs/pull/77380 and https://github.com/NixOS/nixpkgs/pull/77432 haven been merged.
