### ISSUE TITLE
Does Varlink solve tight coupling between daemon and client?

### ISSUE THREAD

**Issue by nyarly** [target/lorri#276]
@curiousleo I've noticed in older version of Lorri that if the daemon and client aren't the same executable, there are errors related to serialization. Does varlink address that?

**Comment by curiousleo** [comment]
Hi! No, we've introduced Varlink only for the fact that it's a smallish existing RPC library, and we didn't want to write / maintain our own.

There are no compatibility guarantees for the wire protocol - that's also why it isn't documented.

That is not to say that this cannot change in the future, but that's the situation for the moment. Hope that helps.

**Comment by nyarly** [comment]
The older solution (bincode over raw sockets) was very brittle. As I'm digging into varlink, it looks like it always serializes as JSON, which sounds like it would at least tolerate varying builds that hadn't changed the interface defnition file.

Does Varlink have any facility for evolving the interface?

**Comment by curiousleo** [comment]
> There are no compatibility guarantees for the wire protocol - that's also why it isn't documented.

I should clarify: as the authors of lorri, we give no guarantee that the protocol will only change in a backward-compatible way. There may be ways of evolving the protocol in a backwards compatible way with Varlink, but for the moment, we will always assume that the lorri client and daemon have the same version.

Incompatibility between a lorri client and a lorri daemon that do not have the same version is not a bug.

**Comment by Profpatsch** [comment]
Yeah, the socket is internal.
