### ISSUE TITLE
readme possibly outdated?

### ISSUE THREAD

**Issue by pmiddend** [target/lorri#277]
The Readme says to run `lorri init` to generate a `shell.nix` and an `.envrc` file. There is no command for that. Did it exist at some point? Do I have the wrong lorri version? It says 0.1.0. What shall I do instead?

**Comment by curiousleo** [comment]
Hi! Unfortunately the version "0.1.0" doesn't say much at all right now. We're working on formalising the release process to the point where the version is set to something meaningful: https://github.com/target/lorri/issues/269.

If you're getting lorri from a NixOS channel (`nixos-unstable` or `nixos-19.09`), we've just updated the version there: https://github.com/target/lorri/issues/272, so one way to fix the non-existence of `lorri init` would be to upgrade it.

**Comment by pmiddend** [comment]
Weird. I installed the lorri service via home-manager. Shouldn't this get a recent-enough version of lorri?

**Comment by curiousleo** [comment]
> Weird. I installed the lorri service via home-manager. Shouldn't this get a recent-enough version of lorri?

I believe it should.
 
> Globally, I'm using nixos-unstable.

`nixos-unstable` now has the version released last week: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/misc/lorri/default.nix#L17

**Comment by pmiddend** [comment]
Ah, my bad. I installed lorri basically when it came out months ago using `nix-env -i`. So `nix-env -e` and then `home-manager switch` solved my problem!
