### ISSUE TITLE
Tag existing releases

### ISSUE THREAD

**Issue by curiousleo** [target/lorri#280]
It would be good to tag releases we've made so far.

```bash
git tag unstable-2019-10-30 03f10395943449b1fc5026d3386ab8c94c520ee3
git push origin unstable-2019-10-30
git tag unstable-2020-01-09 7b84837b9988d121dd72178e81afd440288106c5
git push origin unstable-2020-01-09
```

See https://github.com/NixOS/nixpkgs/commits/master/pkgs/tools/misc/lorri/default.nix for the releases we've made so far.

**Comment by curiousleo** [comment]
I don't have write access to the repo. @Profpatsch or @grahamc, could you run the commands in the description to tag existing lorri releases, please?

**Comment by grahamc** [comment]
Done, thanks!
