### ISSUE TITLE
lorri daemon panics at Started(ProjectAdded(Shell(

### ISSUE THREAD

**Issue by schmittlauch** [target/lorri#284]
**Describe the bug**

lorri daemon, running as a systemd user service, crashes when cd-ing into a direnv + lorri enabled directory.
According to the logs it panics at the step `INFO build status, message: Started(ProjectAdded(Shell("/path/to/shell.nix"))), lorri_version: 1`

**To Reproduce**

I'm running `lorri daemon` inside a customly configured systemd user service, as the one included in home-manager doesn't work properly (debugging this in rycee/home-manager#990)

My lorri daemon service is defined like this in home-manager:

```nix
  systemd.user.services.lorri = {
    Service.ExecStart = lib.mkForce "${pkgs.lorri}/bin/lorri -v daemon";
    Install.WantedBy = [ "default.target" ];
  };
  systemd.user.startServices = true;
```

1. enable custom lorri service in home manager (and start service if necessary) 
2. change into a lorri-enabled project directory, which triggers direnv to contact the lorri daemon
3. Observe a panic message in the lorri.service log: `journalctl --user -u lorri.service`

**Expected behavior**

Just running `lorri daemon` from a shell instead of wrapping it into a systemd service is not affected by this issue.
I expect the lorri daemon to still work when being run as a systemd user service.

**Metadata**

```
name = 'lorri'
operating_system = 'unix:Unknown'
crate_version = '0.1.0'
explanation = '''
Panic occurred in file 'src/libcore/result.rs' at line 999
'''
cause = 'Error cause could not be determined by the application.'
method = 'Panic'
backtrace = '''

   0: 0x5555a1163129 - lorri::thread::Pool::join_all_or_panic::h6044e2329ae8dbf7
   1: 0x5555a1183e4d - lorri::daemon::Daemon::serve::h6ea8367dcbaf0cc3
   2: 0x5555a113ea17 - lorri::ops::daemon::main::h672606e7ac529a84
   3: 0x5555a10d01b5 - lorri::main::h35023ddcbfd20bcd
   4: 0x5555a10db123 - std::rt::lang_start::{{closure}}::hb93ab8b2510e10c3
   5: 0x5555a132f833 - std::panicking::try::do_call::h1a18c38a7e31fab7
   6: 0x5555a134a33a - __rust_maybe_catch_panic
   7: 0x5555a1338609 - std::rt::lang_start_internal::hdff6d5cfd7ec0d0f
   8: 0x5555a10d26c5 - main
   9: 0x7f523ee57b8e - __libc_start_main
  10: 0x5555a10c31ea - _start
  11:        0x0 - <unknown>'''
```

```console
$ lorri info
lorri version: 1
Lorri Project Configuration

expression: shell.nix
```

```console
$ uname -a
Linux exmachina 4.19.95 #1-NixOS SMP Sun Jan 12 11:17:30 UTC 2020 x86_64 GNU/Linux
```

**Additional context**

The crash seems to be unrelated from the actual content of shell.nix, as it happened for all 3 different projects I tried with.
For completeness sake, I still attach one of the shell.nix files:

```nix
{ pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
  buildInputs = with pkgs; [
    pandoc
    haskellPackages.pandoc-citeproc.out
  ];
}
```

**Comment by curiousleo** [comment]
Sounds similar to https://github.com/target/lorri/issues/283.

> Just running `lorri daemon` from a shell instead of wrapping it into a systemd service is not affected by this issue.

That's a very helpful observation, thank you.

**Comment by schmittlauch** [comment]
Forgot to add: I'm running both NixOS and home-manager as release-19.09

**Comment by pauldub** [comment]
I've had a similar crash, but with the following log line:

```
lorri[8342]: thread 'accept-loop' panicked at 'called `Result::unwrap()` on an `Err` value: Message(R(Deserialize(Custom("i
nvalid value: integer `1701651067`, expected variant index 0 <= i < 1"))))', src/libcore/result.rs:999:5
```

When lorri is started with `lorri daemon` no error occurs

**Comment by Profpatsch** [comment]
@schmittlauch Were you able to find the issue?

**Comment by schmittlauch** [comment]
@Profpatsch No, haven't had the time to look into that so far. I'll do that after upgrading to 20.03 at last.

**Comment by schmittlauch** [comment]
This crash no longer happens in NixOS 20.03 with lorri 1.0.0
