### ISSUE TITLE
Create man page

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#330]
**Feature description**

I’ve come to expect that valuable tools have a good man page. Personally I get a bad feeling about a tool if it doesn’t have at least a small one. We should add one.

**Target users**

Just normal unix users, when looking up man pages for tools is a normal part of the workflow.
Compared to looking at `--help` output:

- it lists *everything*, thus makes it possible to search for functionality
- It can have more verbose descriptions of what a command does
- It can have plain-text sections
- *Examples*

The man page is (and should be) the first place to look to get a overview of what the tool does (and maybe links to tutorials, further reading, &c.)

**Comment by curiousleo** [comment]
We certainly don't have to use this, but this may be a useful pointer for whoever attacks this: https://github.com/rust-cli/man

**Comment by tshaynik** [comment]
Looks like this issue got resolved with this commit: 78f2913ca15855ddf12a5980a687cc7e3a805a1e

Should this be closed?

**Comment by curiousleo** [comment]
@tshaynik well spotted :)
