### ISSUE TITLE
lorri doesn't seem to be installable using home-manager

### ISSUE THREAD

**Issue by 573** [target/lorri#336]
**Describe the bug**

lorri doesn't seem to be installable using home-manager as described in the readme.

**To Reproduce**

1. Add lorri to services in home.nix
2. Add direnv to programs in home.nix
3. Add bash hooks etc.
4. Run home-manager switch

**Expected behavior**
lorri / direnv should be installed and available

**Metadata**

```console
$ uname -a
Linux ICEMACHINE 4.4.0-17134-Microsoft #1130-Microsoft Thu Nov 07 15:21:00 PST 2019 x86_64 GNU/Linux
```

**Additional context**

home-manager breaks the build saying:
```console
error: lorri is not stable yet. Please go to https://github.com/target/lorri and follow the installation instructions there, for the time being.
```

**Comment by curiousleo** [comment]
Hi @573, thanks for this report. Would you mind opening it against the `home-manager` repo at https://github.com/rycee/home-manager?

If you do, let's still keep this issue open as a tracking issue.

**Comment by 573** [comment]
@curiousleo done.

**Comment by Profpatsch** [comment]
@573 Are you on a recent version of nixpkgs? That error is long-gone, on current master as well as 19.09.

**Comment by curiousleo** [comment]
> @573 Are you on a recent version of nixpkgs? That error is long-gone, on current master as well as 19.09.

Reference: https://github.com/NixOS/nixpkgs/pull/72889/files#diff-036410e9211b4336186fc613f7200b12L8441

**Comment by 573** [comment]
@Profpatsch you're right, `home-manager switch -I nixpkgs=channel:nixos-19.09` works.
