### ISSUE TITLE
Failed to evaluate my project(dependencies, envs,...) and uncomplete cache directory

### ISSUE THREAD

**Issue by LinArcX** [target/lorri#354]
**Describe the bug**
Hi. lorri can't evaluate dependencies, envs,.. that i've defined inside `shell.nix`.

**To Reproduce**

1. Install void linux, and after that [install nix like this](https://github.com/void-linux/void-packages/issues/18970#issuecomment-601327434)
2. install direnv from void repo.
3. [install lorri like this](https://github.com/target/lorri#setup-on-other-platforms).
4. [clone this test repo](https://github.com/LinArcX/mxl)
5. open new terminal and run: `lorri daemon`
6. open terminal in your current project directory to load envs from .envrc.
7. go to lorri cache directory: `~/.cache/lorri`. there is a __cas__ file [contains](https://gist.github.com/LinArcX/4f2cb6ee90ac2fc8d857095ffe4bc597) and in gc_roots directory there is another directory with a long hash name and inside it there is another directory called gc_root. But inside gc_root there is nothing!

**Expected behavior**
Lorri should watch and monitor my project and __load dependencies__ and __environment variables__ that i defined in shell.nix properly.

Edit: Actually sometimes lorri can create derivation and load dependencies properly, But it can't set environment variables that i'v set [like this](https://github.com/LinArcX/mxl/blob/master/shell.nix#L11).

**Metadata**
I'm using lorri + nix + direnv on my [void-linux](https://voidlinux.org/) machine.(All of them updated)

This is the ouput of `lorri daemon`:
```
Mar 21 13:14:02.598 INFO ready
Mar 21 13:14:05.211 INFO build status, message: BuildEvent(Started { nix_file: Shell("/mnt/D/workspace/c/projects/mxl/shell.nix"), reason: ProjectAdded(Shell("/mnt/D/workspace/c/projects/mxl/shell.nix")) })
```

```console
╰ lorri info --shell-file shell.nix 
lorri version: 1.0
gc roots do not exist, shell_gc_root: "/home/linarcx/.cache/lorri/gc_roots/9e43cce58d5bcd29adb7caa0e554c6cc/gc_root/shell_gc_root"
```

```console
$ uname -a
Linux gnu_linux 5.4.26_1 #1 SMP PREEMPT Wed Mar 18 12:43:43 UTC 2020 x86_64 GNU/Linux
```

**Comment by Profpatsch** [comment]
Can’t reproduce, with `lorri daemon` and `direnv allow in your repo:

```
philip@shiki ~/t/mxl (master)> printenv NAME
mxl
philip@shiki ~/t/mxl (master)> printenv CMAKE
/nix/store/yvq7zkvkmycdg22l4lsr4nn20174gi74-cmake-3.16.3/bin/cmake
philip@shiki ~/t/mxl (master)> printenv CMAKE_RELEASE
-DCMAKE_BUILD_TYPE=RELEASE ../;
```

Same result with `lorri shell`, seems to work just fine.

**Comment by LinArcX** [comment]
Yeah, actually my setup of nix was wrong. I re-install nix and now everything works like a charm :)
