### ISSUE TITLE
[RFC] Stabilize the Event fields as they are

### ISSUE THREAD

**Issue by nyarly** [target/lorri#360]
## Context 

In https://github.com/target/lorri/pull/183#discussion_r373508954, the idea of changing the Event varlink message to try to deliver a kind of type safety within the restrictions of Varlink was proposed.

When those messages were being converted into Rust enums, there was appeal to this. It would make it possible to use a single top-level `TryInto` implementation, and all the sub-messages could be `Into`.

The current plan being discussed makes `Event` a part of the public interface, to be consumed e.g. by jq in bash.

## Proposal

Apart from breaking dependency on Varlink types that will remain private, the `Event` message in a public context remains as-is, with fields being optional as high in the tree as possible.

This is based on the observation that the trade off is between making a single evaluation for the existence of e.g. a `started` field, and then the related fields are guaranteed to be present, versus the implicit communication that e.g. the `nix_file` field, when present` means the same thing in different contexts. Regardless of the approach chosen, the only safety available is provided by comments in the varlink definition.

**Comment by nyarly** [comment]
Separately from the RFC itself, I'd say that I feel that the choice between approaches here is largely one of personal preference. The circumstances around types in Varlink doesn't provide a clearly preferable solution.

I'd argue that scripting-language consumers are more likely to prefer the clarity around a single `nix_file` field, and consider an extra level of indirection more of a hassle than a preference.

**Comment by curiousleo** [comment]
I remain unconvinced, but I'm happy to back off at this point. If this turns out to have been a mistake, we'll just release a new major version.

**Comment by nyarly** [comment]
I opened the RFC specifically to work through the idea. If there's something I'm not seeing, I'd love to hear it.

**Comment by Profpatsch** [comment]
> with fields being optional as high in the tree as possible

Does that mean having *more* fields being `Option` internally (instead of proper enums) or *less* fields?

**Comment by nyarly** [comment]
The fields in question are only Option to serialize for `stream_events`; I can't think of a place where Lorri consumes them itself except to `try_from` as part of transmitting them.

The fields in question are currently Option, so it's "the same number." @curiousleo's proposal would have a small reduction in the number of Option fields, but they'd be structs that contain the same ultimate number of fields.

Specifically, the biggest change would be to this message: https://github.com/target/lorri/blob/master/src/com.target.lorri.varlink#L39-L44

Which would become something like
```
type Failure (
    kind: (io, spawn, exit, output),
    io: ?IOFail,                # iff kind == io, has msg field
    spawn: ?SpawnFail, # iff kind == spawn, has msg, cmd
    exit: ?ExitFail,           # iff kind == exit, has cmd, status, logs
    # no extra information for kind == output
)
```

**Comment by Profpatsch** [comment]
Ah, so just the canonical representation of sum types. Makes sense.

```
>     # no extra information for kind == output
```

For homogenicity, add that field as an empty struct/record, so that we can add fields later and “pattern matching” for clients works.

**Comment by nyarly** [comment]
So, @Profpatsch your feeling is that we should change the Event format and implement #358 ?

**Comment by curiousleo** [comment]
Thanks @Profpatsch for introducing the vocabulary I was missing here!

I think of `Failure` as a sum type. Unfortunately, varlink only has records (product types). The most obvious way to emulate sum types via records is to say "exactly one of these fields will be populated". This way, we can get a hierarchy where every record is either "sum-ish" (exactly one field set) or "product-ish" (all fields set).

I said I'd back out of the discussion because I think this boils down to personal preference to some degree. I am personally used to thinking in terms of sum and product types, and combinations of optional fields that are populated in particular cases confuse me. I also think that documentation is easier if you can say "exactly one of the fields will be set" or "all of the fields will be set" for every varlink type. That's why I made the proposal to restructure the varlink representation in the first place.

I recognise that these changes come at the cost of more deeply nested messages as compared to the "flat message" current state of affairs.

**Comment by Profpatsch** [comment]
>  I also think that documentation is easier if you can say "exactly one of the fields will be set" or "all of the fields will be set" for every varlink type.

Can you say “exactly one” in varlink?

I think “have an enum with all possibilities and an optional field for each enum item that required to be populated if this enum item is set” is a good representation of a sum type.

**Comment by curiousleo** [comment]
> Can you say “exactly one” in varlink?

No. Also see https://varlink.org/Interface-Definition.

**Comment by nyarly** [comment]
I appreciate the context and distinction between product and sum types. I'm coming around to approximating a sum type as a hedge against future-proofing the interface, even if we can't rely on varlink to guarantee the type.

I do want to stress that the argument against isn't so much the deep nesting that results. I think some users will find that unpleasant and not understand the reason why, but there's worse things happen at sea (or in API design.)

The concern is the documentation behavior of the interface. It's not clear that e.g. the `io.msg` is the same thing as `spawn.msg`, as it is when there's a top-of-tree `msg`, which is clearly reflexively the same.

The ability to make future changes to the interface are more important, though, IMO. So I think we're agreed on rejecting this RFC and altering the Event fields to behave as a kinda-sorta sum-of-products type.

**Comment by curiousleo** [comment]
That's great to hear. Thank you for your patience @nyarly as I struggled to find the right vocabulary to express my thoughts on this.
