### ISSUE TITLE
getting lorri to work with ghcide in emacs

### ISSUE THREAD

**Issue by zeta-00** [target/lorri#377]
**Describe the bug**

hello there, i setup ghcide inside of a a shell.nix, and use it with lorri in emacs, anyways, ghcide works fine, the only issue that i'm having is:
ghcide is not recognizing the haskell pkgs/modules that i have installed, for example when i try to import a module, i get a ghcide error saying that the module is not being recognized? when i go into a regular nix-shell, nix builds the hoogle/haddock database, so maybe this issue has to do with lorri?
here's the 2 shell.nix files that i'm trying to use:
https://dpaste.org/2ARz
https://dpaste.org/uM64

**To Reproduce**

1. ...
2. ...
3. ...

**Expected behavior**

**Metadata**

```console
$ lorri info
<please paste output here>
```

```console
$ uname -a
<please paste output here>
```

**Additional context**

**Comment by Profpatsch** [comment]
Same as on the other issue:

Could you please fill out the issue template and use an inline code-block for your shell.nix? The dpaste link is already deleted.

**Comment by zeta-00** [comment]
ok, i found a workaround to get this shell.nix working, after finally fixing the nix errors, when i run this in a nix-shell, it automatically opens up emacs, and when i cd into my project that has been initialized by lorri, ghcide is a able to recognize the haskell pkgs/modules that i have installed, go ahead and close this issue, pasted below is the shell.nix file:

let
  pkgs = import <nixpkgs> {};
in
with pkgs;
mkShell
  {
    buildInputs = with pkgs;
      [
        
        hello
        figlet


        (haskell.packages.ghc865.ghcWithHoogle (hpkgs: with hpkgs;
          [
            control
            text

            yesod

            brick
          ]))
        
        # ghcide-nix installation:
        (import (builtins.fetchTarball "https://github.com/cachix/ghcide-nix/tarball/master") {}).ghcide-ghc865
      ]; # end of buildInputs

    

    shellHook =
      ''
         export PS1='\n\[\033[1;32m\][\[\e]0;nix-shell: \W\a\]nix-shell:/\W]\$ \[\033[0m\]'
         export EDITOR="$(emacs)"

         export HIE_HOOGLE_DATABASE="$(cat $(which hoogle) | sed -n -e 's|.*--database \\(.*\\.hoo\\).*|\\1|p')";
         export NIX_GHC="$(which ghc)";
         export NIX_GHCPKG="$(which ghc-pkg)";
         export NIX_GHC_DOCDIR="$NIX_GHC/../../share/doc/ghc/html";
         export NIX_GHC_LIBDIR="$(ghc --print-libdir)";
      '';
  } # end of mkShell

**Comment by zeta-00** [comment]
@Profpatsch    ^

**Comment by zeta-00** [comment]
@Profpatsch , there's probably a better approach to doing this, but i'm glad it's at least working
