### ISSUE TITLE
lorri is missing functionality for ghcide in emacs:

### ISSUE THREAD

**Issue by zeta-00** [target/lorri#378]
**Describe the bug**

with this shell.nix: https://dpaste.org/NcYb , when i run nix-shell in terminal, emacs opens up into the directory and ghcide is able to recognize modules when i try to import, but when i try to use   (lorri+direnv+emacs-direnv) in emacs, ghcide works but it's not able to recognize modules, like when i try to import Yesod for example.

Any tips to help me fix this will be greatly appreciated, thanks in advance !!!
**To Reproduce**

1. ...
2. ...
3. ...

**Expected behavior**

**Metadata**

```console
$ lorri info
<please paste output here>
```

```console
$ uname -a
<please paste output here>
```

**Additional context**

**Comment by Profpatsch** [comment]
Could you please fill out the issue template and use an inline code-block for your shell.nix? The dpaste link is already deleted.

**Comment by zeta-00** [comment]
I figured it out in the other issue: https://github.com/target/lorri/issues/377  , go ahead and close this issue
