### ISSUE TITLE
Lorri broken prompt on nested shells, bash vs bashInteractive and its cohort of issues

### ISSUE THREAD

**Issue by deliciouslytyped** [target/lorri#383]
See also https://github.com/NixOS/nixpkgs/issues/59209#issuecomment-617103619 , running shells in direnv+Lorri on NixOS runs into the usual bash vs bashInteractive issues with broken prompts.

It can be worked around by adding bashInteractive to the mkShell.

**Comment by kaleocheng** [comment]
I also got this issue on NixOS

.envrc:
```
eval "$(lorri direnv)"
layout python2
```

shell.nix
```
let
  pkgs = import <nixpkgs> {};
in
pkgs.mkShell {
  shellHook = ''
    unset SOURCE_DATE_EPOCH
  '';
}
```


when I run a nested bash inside the direnv+Lorri bash, I got a broken prompt:

```
$ bash 
complete: command not found
bind: command not found
bind: command not found
bash: set: vi: invalid option name
\[\]\[\] impure \[\]\[\]\[\]\[\]\[\] ~ \[\]\[\]\[\]\[\]\[\] \[\]\[\]\[\]\[\]\[\] … \[\]\[\]\[\]\[\]\[\] $
```

@deliciouslytyped  really appreciate if you could show more details about the workaround

**Comment by Profpatsch** [comment]
```
let
  pkgs = import <nixpkgs> {};
in
pkgs.mkShell {
  shellHook = ''
    unset SOURCE_DATE_EPOCH
  '';
  buildInputs = [ pkgs.bashInteractive ];
}
```

should work around this.

Actually I think we should add that to the default `shell.nix` we generate, since it’s a known problem.
