### ISSUE TITLE
emacs environment variables not being detected problem in: (lorri+direnv+emacs-direnv) configuration?

### ISSUE THREAD

**Issue by zeta-00** [target/lorri#384]
hello there, i integrated lorri with emacs, and i'm having an issue where emacs is not detecting some environment variables: here's the r/nixos reddit post: https://www.reddit.com/r/NixOS/comments/g8jv8k/emacs_environment_variables_not_being_detected/

**Comment by zeta-00** [comment]
also, i'm guessing ghcide is not able to detect the haskell Modules like Yesod in the yesod package, because emacs is not detecting the environment variables?

**Comment by zeta-00** [comment]
at this point, i have no idea how to fix this problem

**Comment by Profpatsch** [comment]
Would you please move the issue description from reddit to this issue? Thank you.

**Comment by zeta-00** [comment]
i have (lorri+direnv+emacs-direnv) setup which works great. when i open up emacs, it detects my user's shell environment variables(from home.nix's shell) like it's supposed to, but when i cd into a project that has been initialized by lorri, the isolated shell's shellHook environment variables in the shell.nix of the project are not being detected(running: `M-x getenv` on environment variables returns nothing), so as a workaround, i placed: `export EDITOR="$(emacs)"` in the shellHook, then in a terminal i cd'd into the directory of that project which is initialized by lorri, then executed the nix-shell command, which then opened emacs with everything working correctly(with `both` my user's global (home.nix's shell) environment variables and the isolated project's local(shell.nix shell(shellHook)) environment variables being detected by emacs.

(the people in the #emacs channel told me that you can have only one emacs process per altered environment)

so my question is:

is there something that i can setup, so that i can just open up emacs, cd into a directory with a project that's been initialized by lorri, where emacs will automatically detect the environment variables of the associated shellHook in the shell.nix file of the project directory, so that emacs will have both the global and local environment variables?

that would save me from having to manually do those other steps over and over again

(note: ghcide is not detecting modules like Yesod from the haskell package yesod, which i'm guessing also corresponds with environment variables not being detected by emacs)

thanks in advance for the help

i have bash shell enabled in home.nix, and here's my shell.nix file which generates a new shell in isolation:

let

pkgs = import <nixpkgs> {};

in

with pkgs;

mkShell

{

buildInputs = with pkgs;

[

(haskell.packages.ghc865.ghcWithHoogle (hpkgs: with hpkgs;

[

control

text


yesod

]))

# ghcide-nix installation:

(import (builtins.fetchTarball "https://github.com/cachix/ghcide-nix/tarball/master") {}).ghcide-ghc865

]; # end of buildInputs


shellHook =

''

export EDITOR="$(emacs)"


export HIE_HOOGLE_DATABASE="$(cat $(which hoogle) | sed -n -e 's|.*--database \\(.*\\.hoo\\).*|\\1|p')";

export NIX_GHC="$(which ghc)";

export NIX_GHCPKG="$(which ghc-pkg)";

export NIX_GHC_DOCDIR="$NIX_GHC/../../share/doc/ghc/html";

export NIX_GHC_LIBDIR="$(ghc --print-libdir)";

'';

} # end of mkShell

**Comment by zeta-00** [comment]
@Profpatsch , ok, i pasted my issue here, it's a hassle always having to manually run nix-shell to open up emacs with shellHook's environment variables correctly detected by emacs.

so, is there a simple way to fix this issue or automate these steps?

let me know,
thanks in advance !!!

**Comment by Profpatsch** [comment]
`lorri direnv` runs the shell hook, but inside of a nix build, not the user shell.

You can work around this by adding the environment setup you want to do in your `.envrc` file instead. 

I opened a documentation issue in https://github.com/target/lorri/issues/390

**Comment by zeta-00** [comment]
@Profpatsch , thanks for the help, after running lorri shell, everything seems to be working correctly. apologies i did not see lorri shell in the documentation, i stumbled upon it when running lorri, in which i saw lorri shell towards the bottom of the documentation.

go ahead and close this issue.
