### ISSUE TITLE
README contradictory: Does "services.lorri.enable = true;" install direnv, too, or not?

### ISSUE THREAD

**Issue by das-g** [target/lorri#388]
**Describe the bug**

The README.md [currently says in section "Setup on NixOS or with `home-manager` on Linux"](https://github.com/target/lorri/tree/a67121895ce3c2b4af0adc5604e756ddfc1fb2fa#setup-on-nixos-or-with-home-manager-on-linux)

> 1. **Enable the daemon service.** Set `services.lorri.enable = true;` in your
>    NixOS [`configuration.nix`][nixos-service] or your home-manager
>    [`home.nix`][home-manager-service].
> 
>    This will automatically install both the `lorri` command and `direnv`
>    (both required for the next steps).

_So it seems that enabling that option should install `direnv`, too._

However, in the next step, the README.md continues

> 2. **Install direnv.** Add `pkgs.direnv` to `environment.systemPackages` in
>    your NixOS `configuration.nix` or to `home.packages` in your home-manager
>    `home.nix`.

_So it seems this additional step is needed to install `direnv`._

**That's contradictory.**

Setting only the `services.lorri.enable = true;` without adding the package and then rebuilding NixOS reveals that that indeed only installs and enables lorri, but in fact **doesn't install `direnv`**. (So currently step 2 is right, while step 1 gives the right instructions but makes an untrue claim.) Depending on whether the option is _supposed_ to also pull in direnv or not, it seems we have either only a lorri documentation bug (because the documentation is contradictory to itself) or a lorri documentation bug and a NixOS module bug.

**To Reproduce**

1. Follow the README's instructions for setting up lorri on NixOS
2. Be confused

**Expected behavior**

Instructions don't unnecessarily confuse the reader.confused

**To reproduce what actually is the case**

On a NixOS system without `direnv` already installed:

1. **Enable the daemon service.** Set `services.lorri.enable = true;` in your
   NixOS [`configuration.nix`][nixos-service]. (I didn't test with home-manager.)
2. Do **not** add `pkgs.direnv` to `environment.systemPackages` in
   your NixOS `configuration.nix` nor to `home.packages` in your home-manager
   `home.nix` nor install it any other way.
3. `sudo nixos-rebuild switch`
4. Observe that the `direnv` command still isn't available

**Metadata**
> Did lorri crash?

No.

```console
$ lorri info
error: The following required arguments were not provided:
    --shell-file <nix_file>

USAGE:
    lorri info --shell-file <nix_file>

For more information try --help
```
(I don't have a lorri-enabled project, yet.)

```console
$ uname -a
Linux NB-TT-120488 5.4.35 #1-NixOS SMP Thu Apr 23 08:36:46 UTC 2020 x86_64 GNU/Linux
```

**Additional context**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.1619.ab3adfe1c76 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1619.ab3adfe1c76"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

[home-manager-service]: https://rycee.gitlab.io/home-manager/options.html#opt-services.lorri.enable
[nixos-service]: https://nixos.org/nixos/options.html#services.lorri.enable

**Comment by curiousleo** [comment]
Possibly the clearest and most actionable ticket I've ever seen. Thank you very much @das-g!

On https://github.com/NixOS/nixpkgs/pull/85144 there was a discussion about making the Readme true, that is, adding `direnv` as a dependency. This was deemed not to be a good idea.

Then @candeira kindly proposed https://github.com/target/lorri/pull/381, which changes the Readme to reflect reality instead. It somehow fell under the table, I don't know why. I've merged it now. I believe that fixes this issue.
