### ISSUE TITLE
ihaskell not working in (lorri+direnv+emacs-direnv) setup?

### ISSUE THREAD

**Issue by zeta-00** [target/lorri#394]
hello there, i finally got the hang of this (lorri+direnv+emacs-direnv) setup, when using the `lorri shell` command with this setup and my projects, everything seems to be working nicely, but for some reason i'm having issues getting ihaskell to work in emacs(emacs-ipython-notebook), so i don't have to re-paste everything, here's the issue that i posted in the ein repo, those devs are not that familiar with nix side of this:

https://github.com/millejoh/emacs-ipython-notebook/issues/708

i don't think that there is anything wrong with the shell.nix file that i'm using for ihaskell, but, i'll paste it here anyways, if any of you want to take a look:

let
  pkgs = import <nixpkgs> {};
in
with pkgs;
mkShell
  {
    buildInputs = with pkgs;
      [
        (let
          ihaskell = fetchFromGitHub
            {
              owner = "gibiansky";
              repo = "IHaskell";
              rev = "a1e415e45f6a1fe61a455459f9e6036591bc2c47";
              sha256 = "1ll27jqnssdxjsfcn2ll0x95kwjk6rhfnsxsdsh03izq95hxys1p";
            };
         in import "${ihaskell}/release.nix"
           {
             compiler = "ghc883";
             nixpkgs = pkgs;
             packages = self: with self;
               [
                 ihaskell
                 ihaskell-aeson
                 # ihaskell-basic
                 ihaskell-blaze
                 # ihaskell-charts
                 # ihaskell-diagrams
                 # ihaskell-display
                 # ihaskell-gnuplot
                 ihaskell-graphviz
                 ihaskell-hatex
                 # ihaskell-hvega
                 # ihaskell-inline-r
                 ihaskell-juicypixels
                 ihaskell-magic
                 # ihaskell-parsec
                 # ihaskell-plot
                 # ihaskell-rlangqq
                 # ihaskell-widgets
               ];
           }
        )
      ];
    
    shellHook =
      ''
         export EDITOR="$(emacs)";
      '';
    
  } # end of mkShell

**Comment by zeta-00** [comment]
and sorry about the formatting of that shell.nix file, i don't know why github re-formats it like that.

**Comment by zeta-00** [comment]
also, i tested out ihaskell in a web browser and it works fine, for some reason it does not want to work in emacs with this setup?

**Comment by dickmao** [comment]
It's not ihaskell that emacs can't find.  It's jupyter.  Incidentally your symptoms are precisely https://github.com/syl20bnr/spacemacs/issues/2294.  Posting at wbolster/emacs-direnv is probably better than here.  Unfortunately, I don't think you know enough about emacs, nix, or UNIX in general to sufficiently describe the problem.  We'll keep trying I guess.

**Comment by zeta-00** [comment]
@dickmao , thanks for the link, i'll check that out as well.

**Comment by Profpatsch** [comment]
> It's not ihaskell that emacs can't find. It's jupyter. Incidentally your symptoms are precisely [syl20bnr/spacemacs#2294](https://github.com/syl20bnr/spacemacs/issues/2294). Posting at wbolster/emacs-direnv is probably better than here. Unfortunately, I don't think you know enough about emacs, nix, or UNIX in general to sufficiently describe the problem. We'll keep trying I guess.

@dickmao thanks for jumping in, let’s keep personal comments to a minimum though.

I suspect we can close? Feel free to reopen.
