### ISSUE TITLE
`lorri shell` doesn't support changing the zsh configuration directory at startup

### ISSUE THREAD

**Issue by energizah** [target/lorri#398]
**Describe the bug**

lorri [looks up the `ZDOTDIR` environment variable](https://github.com/target/lorri/blob/make-commands-use-hyphens/src/ops/start_user_shell.rs#L72) and stores its value as [`ZDOTDIR_OR_HOME`](https://github.com/target/lorri/blob/make-commands-use-hyphens/src/ops/start_user_shell.rs#L71). In typical cases `ZDOTDIR` is a *shell variable*, not an environment variable, so `ZDOTDIR_OR_HOME` will be set to the value of `$HOME`. 

Then lorri [sources the `.zshenv` file](https://github.com/target/lorri/blob/make-commands-use-hyphens/src/ops/start_user_shell.rs#L63). The code in `.zshenv` might change the value of `ZDOTDIR` shell variable. But then lorri [uses the old `ZDOTDIR_OR_HOME` location](https://github.com/target/lorri/blob/make-commands-use-hyphens/src/ops/start_user_shell.rs#L65), not the new `ZDOTDIR` location. So if `ZDOTDIR` is changed in `.zshenv`, that change will not be observed.

**To Reproduce**

1. `echo ZDOTDIR="$HOME"/.config/zsh > "$HOME"/.zshenv"`
2. `echo HISTFILE="$HOME/.config/zsh/zsh_history >> "$HOME"/.config/zsh/.zshrc`
3. Open a new shell
5. `echo $HISTFILE` 
See that it shows the adjusted `zsh_history` path.
3. `lorri shell` 
4. `echo $HISTFILE`
See that it's empty.

**Ideas**

It might be enough to simply load the new `ZDOTDIR` after sourcing each file

```zsh
test -f "$ZDOTDIR_OR_HOME/.zshenv" && . "$ZDOTDIR_OR_HOME/.zshenv"
ZDOTDIR_OR_HOME="${ZDOTDIR:-${HOME}}"
test -f "/etc/zshrc"               && . "/etc/zshrc"
ZDOTDIR_OR_HOME="${ZDOTDIR:-${HOME}}"
test -f "$ZDOTDIR_OR_HOME/.zshrc"  && . "$ZDOTDIR_OR_HOME/.zshrc"
```

but I haven't tested it.

**Metadata**

```console
$  lorri --version
lorri 1.0.0
```

```console
$ uname -a
Linux beta 5.4.35 #1-NixOS SMP Thu Apr 23 08:36:46 UTC 2020 x86_64 GNU/Linux
```

**Additional context**

**Comment by curiousleo** [comment]
Thanks for the report @energizah! Looks like zsh handling is even more complicated than I thought ...

Your suggested fix is much appreciated! I think it's really close to fixing the issue.

The problem is that in order to get zsh to source the generated file in the first place, we must set `ZDOTDIR` in the context of the zsh process: https://github.com/target/lorri/blob/896391ed257e6f3cd5bf7a2e802d2761c3be1ff5/src/ops/start_user_shell.rs#L75

As a result, `ZDOTDIR` is always set when the generated startup script runs, namely to the directory containing the script. So we need to unset it first and then add the line you suggested before the line that sources `.zshrc`.

```zsh
ZDOTDIR_OR_HOME="${ZDOTDIR:-${HOME}}"
```

I don't think it is necessary to also do this before sourcing `/etc/zshrc` since the value of `ZDOTDIR_OR_HOME` is irrelevant there.

I'll put up a PR for this.

**Comment by energizah** [comment]
> I don't think it is necessary to also do this before sourcing `/etc/zshrc` since the value of ZDOTDIR_OR_HOME is irrelevant there.

Probably right, though I think it's at least possible for the code in `/etc/zshrc` to use `$ZDOTDIR` and set a new value for it.

**Comment by curiousleo** [comment]
> Probably right, though I think it's at least possible for the code in `/etc/zshrc` to use `$ZDOTDIR` and set a new value for it.

Absolutely. But it is unlikely to read or write `ZDOTDIR_OR_HOME`.

**Comment by berbiche** [comment]
Would the proposed changes allow me to source relative files within my `$ZDOTDIR/.zshrc`?
Currently I have to wrap my sourcing with checks (the dirname part) otherwise `lorri shell` fails.

```console
$ exa -1 --color=auto --group-directories-first --all $ZDOTDIR
.zcompdump
.zprofile
.zshenv
.zshrc
base-zshrc
zaliases

$ bat --pager='' $ZDOTDIR/.zshrc
       File: /home/nicolas/.config/zsh/.zshrc
   1 ~ # Source the base file if $ZDOTDIR is within HOME
   2 ~ if [[ "$(dirname "$ZDOTDIR")" == "$HOME"* ]]; then
   3 ~   . $ZDOTDIR/base-zshrc
   4 ~ fi
   5
   6 ~ fpath=($fpath "${ZDOTDIR}/.zfunctions")
   7
   8   eval "$(starship init zsh)"
   9 + eval "$(direnv hook zsh)"
  10
  11   # Source aliases if ZDOTDIR is $ZDOTDIR within home
  12   if [[ "$(dirname "$ZDOTDIR")" == "$HOME"* ]]; then
  13     . $ZDOTDIR/.zshenv
  14     . $ZDOTDIR/zaliases
  15   fi
  16
  17   unsetopt SHARE_HISTORY
  18   unsetopt share_history
  19 _
  20   if [ -n "${commands[fzf-share]}" ]; then
  21     source "$(fzf-share)/key-bindings.zsh"
  22   fi
  23
  24   if [ -z $ZSH_RELOADING_SHELL ]; then
  25     echo $USER@$HOST  $(uname -srm) \
  26       $(sed -n 's/^NAME=//p' /etc/os-release) \
  27       $(sed -n 's/^VERSION=//p' /etc/os-release)
  28   fi
  29
  30   source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
  31   source "$XDG_CONFIG_HOME/broot/launcher/bash/br"
```

**Comment by curiousleo** [comment]
> Would the proposed changes allow me to source relative files within my `$ZDOTDIR/.zshrc`?

https://github.com/target/lorri/pull/400 has been merged - if you like, you can try building `lorri` from `master` to check! I tried to make it such that `ZDOTDIR` is set iff it would be set without lorri, and observably always has the value it would have had without lorri.

**Comment by berbiche** [comment]
Cloned master (rev. 4a56d6c), `nix-build` lorri and ran `./result/bin/lorri shell`.

My `$ZDOTDIR/.zshrc` is no longer sourced because it does not live in `$HOME`.

I sprinkled some printfs in `src/ops/start_user_shell.rs` and discovered the test `[ -z ${ZDOTDIR_BEFORE+x} ]` would always result in an unset ZDOTDIR variable.

My configuration is correctly sourced only if the test to reset the ZDOTDIR is changed to the following:

```sh
if [ ! -z ${ZDOTDIR_BEFORE} ]; then
    ZDOTDIR="${ZDOTDIR_BEFORE}"
else
    # Unset ZDOTDIR otherwise this configuration file will recursively include itself
    # until it has reached the recursion limit set by ZSH
    unset ZDOTDIR
fi
```

The final file:

```patch
diff --git a/src/ops/start_user_shell.rs b/src/ops/start_user_shell.rs
index 930c9ea..4a47cd4 100644
--- a/src/ops/start_user_shell.rs
+++ b/src/ops/start_user_shell.rs
@@ -61,18 +61,28 @@ PS1="(lorri) $PS1"
                 r#"
 unset RCS # disable automatic sourcing of startup scripts
 
+printf "ZDOTDIR_BEFORE: ${ZDOTDIR_BEFORE}\nZDOTDIR: ${ZDOTDIR}\n"
+printf "Has /etc/zshenv been sourced? ${__ETC_ZSHENV_SOURCED}\n"
+printf "B: ${ZDOTDIR_BEFORE+x}; ${ZDOTDIR_BEFORE}\n"
+
 # reset ZDOTDIR
-if [ -z ${ZDOTDIR_BEFORE+x} ]; then
+if [ ! -z ${ZDOTDIR_BEFORE} ]; then
     ZDOTDIR="${ZDOTDIR_BEFORE}"
 else
+    # Unset ZDOTDIR otherwise this configuration file will recursively include itself
+    # until it has reached the recursion limit set by ZSH
     unset ZDOTDIR
 fi
 
 ZDOTDIR_OR_HOME="${ZDOTDIR:-${HOME}}"
+printf "ZDOTDIR_OR_HOME is ${ZDOTDIR_OR_HOME}\n"
 test -f "$ZDOTDIR_OR_HOME/.zshenv" && . "$ZDOTDIR_OR_HOME/.zshenv"
 test -f "/etc/zshrc"               && . "/etc/zshrc"
+printf "ZDOTDIR_OR_HOME after sourcing is ${ZDOTDIR_OR_HOME}\n"
 ZDOTDIR_OR_HOME="${ZDOTDIR:-${HOME}}"
+printf "Resetting ZDOTDIR_OR_HOME to ${ZDOTDIR_OR_HOME}\n"
 test -f "$ZDOTDIR_OR_HOME/.zshrc"  && . "$ZDOTDIR_OR_HOME/.zshrc"
+printf "Last ZDOTDIR_OR_HOME before setting PS1 ${ZDOTDIR_OR_HOME}\n"
 
 PS1="(lorri) ${PS1}"
 "#,
```
