### ISSUE TITLE
`lorri pin` command

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#40]
@aspiwack writes:
> Pinning nixpkgs is very underused. Mostly because it's a rather painful process (one has to find the commit reference for the current nixpkgs then remember the code snippet to copy/paste in).
> 
> So I imagine that lorri could have a command to do all these things for me.
>
>----
>
> Here is a straw-man proposal:
>
> Pin the project to the current nixpkgs version:
>
>```
> $ lorri pin
>```
>
> Pin the project to the latest nixpkgs-stable:
>
>```
> $ lorri pin nixpkgs-stable
>```
>
> Update the pinned version to the current nixpkgs:
>
>```
> $ lorri pin --update
>```
>
> I'm not sure what it should look like nix-expression-wise. Certainly the pinning action should be in file checked into the version control system. Possibly by modifying the shell.nix file. Or possibly by making a lock.nix file under lorri's control, which you would require the user to call from shell.nix. Something to that effect.

@zimbatm writes:
> for some prior art see:
>
> * https://github.com/nmattia/niv/
> * https://github.com/zimbatm/nix-path

@shlevy writes:
> If we do this it would be good to coordinate with flakes if relevant.

**Comment by Profpatsch** [comment]
This is a cool idea for a drive-by contribution. If somebody wants to take it, we can discuss a design.

**Comment by WhoMeNope** [comment]
I'm missing this functionality sorely. 
I was thinking about the design a bit and maybe this could be just a flag for the init comand (`lorri init --pin`), which would just output `shell.nix` with the [pinning boilerplate](https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs) included, either pointing to the latest commit, or maybe leaving the commit empty for the user to edit.

@Profpatsch, what do you think?

**Comment by Profpatsch** [comment]
@WhoMeNope I think https://github.com/nmattia/niv does all of this and more better than what lorri could ever implement.

We should add a link to it in a “befriended projects” section of the readme.

**Comment by WhoMeNope** [comment]
@Profpatsch Niv is looking great, thanks!
Adding it to the readme so it's easier to find from here would be very nice.
