### ISSUE TITLE
Allow passing arguments to the shell.nix file

### ISSUE THREAD

**Issue by regnat** [target/lorri#416]
**Feature description**

If a project has a `shell.nix` of the form

```nix
{ withHello ? false }:
with import <nixpkgs> {};
mkShell {
  buildInputs = lib.optional withHello hello;
}
```

Then the only way (afaik) to get `lorri direnv` to give me a shell with `hello` available is to create another nix file (`shell2.nix`) calling this `shell.nix` and passing `withHello = true`, and then call `lorri direnv --shell-file shell2.nix`.

It would be nice to be directly able to do something like `lorri direnv --arg withHello true` like with plain `nix-shell`

(for a more concrete use-case, [nix's shell.nix](https://github.com/NixOS/nix/blob/master/shell.nix) has a `useClang` option that I'd like to set to `true`)

**Comment by Profpatsch** [comment]
Personally I don’t think we should copy too much of nix’s command line interface.

What’s the problem with having a second shell file like that? Your `.envrc` would point to it and both would not be versioned, right?

**Comment by regnat** [comment]
> What’s the problem with having a second shell file like that? Your .envrc would point to it and both would not be versioned, right?

Yes, there's no fundamental issue with that. It's just that it feels a bit awkward and complex for what it is. But no big deal indeed and I understand the concern of keeping the cli interface simple
