### ISSUE TITLE
Ctrc-C ing (SIGINT/SIGTERM) the daemon returns status 130/143 instead of 0

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#463]
We should accept at least SIGTERM as valid shutdown request, if not SIGINT (which is useful on the command line).

On the command line it never saves `lorri daemon` in my history, because the return code is not successful.

**Comment by tshaynik** [comment]
Hi! I'm a `lorri` user looking to get involved in contributing, and I'd like to take a look at this as my first issue. Thanks!
