### ISSUE TITLE
Have `lorri` auto-evalute the first time

### ISSUE THREAD

**Issue by grahamc** [target/lorri#53]
When setting up direnv with lorri, it is a bummer to have it fail the first time due to no `watch` runner. It would be cool if `lorri direnv` would auto-evaluate the expressions just the first time.

One concern I have is this might encourage people to _never_ `watch` their project, and thus have ancient dependencies stick around for an eternity.

**Comment by nyarly** [comment]
What if it failed "open" - in other words, if `lorri watch` isn't running, behave like `use nix`?

**Comment by Profpatsch** [comment]
> in other words, if `lorri watch` isn't running, behave like `use nix`?

We do exactly that in lorri itself:
https://github.com/target/lorri/blob/master/.envrc#L7-L17

**Comment by nyarly** [comment]
I've seen several people replace `use nix` with a `lorri` command, so this might not work great in `lorri eval`, but maybe recommending something like it as a recommended `.direnvrc` entry?

**Comment by Profpatsch** [comment]
Closing in favor of https://github.com/target/lorri/issues/99
