### ISSUE TITLE
Mirror nix’s `default.nix` mechanism in path discovery

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#58]
I forgot to post my findings, but _yes_ this is true! Nix doesn't emit `/path/to/default.nix` as the true file, it emits just '/path/to`. A possible solution here is to append  a `/default.nix` when an imported directory is identified.

_Originally posted by @grahamc in https://github.com/target/lorri/pull/21_

We currently watch the whole directory if a user does `import /path/to/directory`. Nix implicitely assumes `/path/to/directory/default.nix` if used with `import`. We should mirror that, to prevent watching too many files.

**Comment by grahamc** [comment]
I think the solution here is to extend LogDatam to have an EvalSource variant:

https://github.com/target/lorri/blob/f93989b34fe605798ecd841cea9c0ba6f8e00f91/src/builder.rs#L128-L131

and then make use of the LogDatum::EvalSource here:

https://github.com/target/lorri/blob/f93989b34fe605798ecd841cea9c0ba6f8e00f91/src/builder.rs#L155-L156

then when we're adding the list of paths at:

https://github.com/target/lorri/blob/master/src/builder.rs#L101

match EvalSource, do an `is_dir` check, and push a `default.nix` if `is_dir` returns true.
