### ISSUE TITLE
Error while following README instructions

### ISSUE THREAD

**Issue by turboMaCk** [target/lorri#59]
Hello. I suspect there must be some issue with README instructions but I can't really say what exactly. I'm using `NixOS` and was following nixos instructions in README.

Issue is with `eval "$(lorri direnv)"` which fails with an error.

```
eval "$(lorri direnv)"
watch_file: command not found
```

which then breaks completely:

```
$ lorri direnv
lorri: command not found
$ eval "$(lorri direnv)"
lorri: command not found
```

In a **new terminal**

```
$ lorri direnv

EVALUATION_ROOT="/home/marek/.cache/lorri/planning-game/gc_root/build-0"

watch_file "$EVALUATION_ROOT"

function declare() {
    if [ "$1" == "-x" ]; then shift; fi

    function punt () {
        :
    }

    function prepend() {
        varname=$1 # example: varname might contain the string "PATH"

        # drop off the varname, so the remaining arguments are the
        # arguments to export
        shift

        # set $original to the contents of the the variable $varname
        # refers to
        eval original=\$$varname

        # effectfully accept the new variable's contents
        export "$@";

        # re-set $varname's variable to the contents of varname's
        # reference, plus the current (updated on the export) contents.
        eval $varname=\$$varname:$original
    }

    # Some variables require special handling.
    #
    # - punt:    don't set the variable at all
    # - prepend: take the new value, and put it before the current value.
    case "$1" in
        # vars from: https://github.com/NixOS/nix/blob/92d08c02c84be34ec0df56ed718526c382845d1a/src/nix-build/nix-build.cc#L100
        "HOME="*) punt;;
        "USER="*) punt;;
        "LOGNAME="*) punt;;
        "DISPLAY="*) punt;;
        "PATH="*) prepend "PATH" "$@";;
        "TERM="*) punt;;
        "IN_NIX_SHELL="*) punt;;
        "TZ="*) punt;;
        "PAGER="*) punt;;
        "NIX_BUILD_SHELL="*) punt;;
        "SHLVL="*) punt;;

        # vars from: https://github.com/NixOS/nix/blob/92d08c02c84be34ec0df56ed718526c382845d1a/src/nix-build/nix-build.cc#L385
        "TEMPDIR="*) punt;;
        "TMPDIR="*) punt;;
        "TEMP="*) punt;;
        "TMP="*) punt;;

        # vars from: https://github.com/NixOS/nix/blob/92d08c02c84be34ec0df56ed718526c382845d1a/src/nix-build/nix-build.cc#L421
        "NIX_ENFORCE_PURITY="*) punt;;

        *)
            export "$@"
            ;;
    esac
}

export IN_NIX_SHELL=1
. "$EVALUATION_ROOT"

unset declare
```

but again evaluating this doesn't work and then breaks lorrri completely:

```
$ eval "$(lorri direnv)"   
watch_file: command not found

$ eval "$(lorri direnv)"        
lorri: command not found
```

**Comment by Profpatsch** [comment]
Are you running this in your normal shell?

`lorri direnv` outputs code that is intended to be put in `.envrc`, which `direnv` calls with functions like `watch_file` set.

What part of the tutorial makes you think it has to be run from your shell? We might have to clarify.

**Comment by turboMaCk** [comment]
Sorry for the dumb issue and late reply. I was just too busy and was not careful enough.

**Comment by Profpatsch** [comment]
You’re not the first to run into this, we need to print a warning.

**Comment by turboMaCk** [comment]
that would be definitely good UX improvement assuming people who can't read manual (like me) can at least read the terminal output :D

**Comment by Profpatsch** [comment]
It’s easy to get wrong and if one does the why is pretty hard to debug (especially if one doesn’t know how direnv works)

**Comment by freddie-freeloader** [comment]
This bit in [here](https://github.com/target/lorri/blob/master/README.md#install) let me to the same mistake.

> Create a file named .envrc in your project's root with the contents:
> 
> eval "$(lorri direnv)"
> 
> Then, run lorri watch. The first time you run lorri watch on a project, wait for it to print Completed before continuing. Leave this terminal open.

**Comment by Profpatsch** [comment]
What exactly lead you to the mistake?

**Comment by turboMaCk** [comment]
@freddie-freeloader do you think [this](https://github.com/target/lorri/blob/bfd8fdeb0e0ba01a60f569edcbef7901cf5e4964/README.md#usage) makes it clearer?

**Comment by turboMaCk** [comment]
@Profpatsch I think seeing a line beginning with `eval` makes a brain go like "this is surely a shell".

I can imagine two possible (cheap) improvements.

1. Adding comment to the source block repeating the important part (as in my PR)
2. Instead of showing file content add shell command to create the file itself:

```
echo 'eval "$(lorri direnv)"' > .envrc
```

**Comment by freddie-freeloader** [comment]
> @Profpatsch I think seeing a line beginning with `eval` makes some brains go like "this is surely a shell".
> 
> I can imagine two possible (cheap) improvements.
> 
>     1. Adding comment to the source block repeating the important part (as in my PR)
> 
>     2. Instead of showing file content add shell command to create the file itself:
> 
> 
> ```
> echo 'eval "$(lorri direnv)"' > .envrc
> ```

This is exactly what I would propose. :relaxed:

In my case the problem was that I copied the code blindly and executed it. I know, this is not smart, but I think this is a common mistake. :slightly_smiling_face:

**Comment by Profpatsch** [comment]
I renamed the issue accordingly. ;)

Joke aside, that’s a valuable lesson to learn for me as a technical writer. Make stuff copy'n'past-able without changing the execution environment midway through.

**Comment by turboMaCk** [comment]
you're definitely right @Profpatsch. Instructions were clear but the receiver was broken. Look at it as if you're dealing with very bad input sensor on the other side (me).
