### ISSUE TITLE
Generalize watch to support running a command, arbitrary nix files

### ISSUE THREAD

**Issue by domenkozar** [target/lorri#64]
I haven't looked at the implementation, but it would be helpful if following worked:

    $ lorri watch -f nix/myfoo.nix --run ls

Motivation: https://github.com/hercules-ci/arion/issues/36

**Comment by Profpatsch** [comment]
I proposed a possible implementation of something similar once we switch away from `lorri watch` to the `lorri daemon` interface. https://github.com/target/lorri/issues/78

**Comment by Profpatsch** [comment]
Closing in favor of #78.
