### ISSUE TITLE
Print warning when `lorri direnv` is called outside of direnv

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#68]
Multiple people have had problems with setting up lorri that boiled down to them trying to source `lorri direnv` outside of the `.envrc` file and missing the direnv stdlib (sometimes even in non-bash shells). One example is https://github.com/target/lorri/issues/59.

We must print a clear warning in that case.

Open question: how to best recognize whether `lorri direnv` is called from `direnv`? cc @zimbatm

**Comment by zimbatm** [comment]
the best way is to check if `DIRENV_IN_ENVRC=1`. This env var is set by direnv before evaluating the `.envrc`.

Alternatively you could `eval "$(direnv stdlib)"` if the env is not set
