### ISSUE TITLE
Display warning that we don’t run shellHooks automatically

### ISSUE THREAD

**Issue by Profpatsch** [target/lorri#72]
Until we figure out a good way to have shell hooks, we should at least display a warning when there is `shellHook` setup in the dependencies the user might depend upon.

That means we have to check if the `shellHook` env variable is defined and also whether any recursive input sets up a shell hook (they forward it in their build outputs via a special `.nix-support` file).

cf https://github.com/target/lorri/issues/7, https://github.com/target/lorri/issues/71

**Comment by chreekat** [comment]
Is it documented? I just came here to open an issue about it :)

**Comment by Profpatsch** [comment]
We’re on the way to actual working support: https://github.com/target/lorri/pull/75

**Comment by grahamc** [comment]
Shell hooks are implemented in master

**Comment by grahamc** [comment]
It'll be in `rolling-release` in a few days. Until then you can do `lorri self-upgrade master`.

**Comment by chreekat** [comment]
Nice work!
