### ISSUE TITLE
lorri daemon: systemd service

### ISSUE THREAD

**Issue by Kiwi** [target/lorri#96]
I've started using the branch with the [`lorri daemon` PR](https://github.com/target/lorri/pull/81) and it's pretty cool! 1 annoyance it carries over from regular lorri is that it still requires an extra sacrificial terminal... with a shell.nix (any shell.nix it seems?) to launch the daemon and remain open. At least it's only 1 as opposed to many.

Anyway, it'd be nice if it could run as a (systemd, etc.) service.

Thanks, everyone! I've been really enjoying lorri

**Comment by Profpatsch** [comment]
I haven’t set up anything in that direction yet, but I suppose a simple `systemd --user` service file should be enough for starters? Or do you have something different in mind?

**Comment by Kiwi** [comment]
I'm not all that familiar with the different ways systemd services can work. So, probably? I don't think it needs to be terribly complex.

This is what I do currently:
````
lorri daemon &> lorri-log.txt &
tail -f lorri-log.txt
````
I do the tail mostly so I know not to close the terminal and I can kill it if i want to use it temporarily without killing the daemon. It works ok but a service would be a little cleaner I think. but more work. I don't know how much work so it might be asking a lot.

**Comment by Profpatsch** [comment]
I have set up a small systemd user service (by copying from another user service with `systemctl cat <service>`), which works pretty well so far:

```
[Unit]
Description=lorri user daemon

WantedBy=graphical-session.target

[Service]
Environment="LOCALE_ARCHIVE=/nix/store/skrsp96qgmkp0b6a565yqg3hsl4s75s4-glibc-locales-2.27/lib/locale/locale-archive"
Environment="TZDIR=/nix/store/fs26ijjyf60l6xxnyg8rkr9b1ld9c7nb-tzdata-2019a/share/zoneinfo"

ExecStart=/home/philip/kot/work/tweag/lorri/target/debug/lorri daemon

Restart=on-failure
RestartSec=5s
```

I’m not exactly sure how we should integrate it into our repo though. `home-manager` could be one way.

**Comment by Profpatsch** [comment]
People have come up with other ways to integrate `lorri watch` into their system, see https://github.com/target/lorri/issues/2

**Comment by IvanMalison** [comment]
@Profpatsch Just wanted to clarify whether you think it definitely makes sense for lorri to be a user unit rather than a system unit. If its going to be a user unit then we wont be able to add a nixos module that handles running the service for you. I added this to my nixos configuration

```
  systemd.services.lorri-daemon = {
    description = "lorri daemon";
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      ExecStart = "${lorri}/bin/lorri daemon";
    };
  };
``` 

but it doesn't quite work, beecause the way lorri looks for paths depends on the current user. This daemon runs as root, and so it stores the daemon file in roots home directory, so e.g. lorri ping_ fails to connect.

**Comment by peterhoeg** [comment]
This works with ```lorri daemon``` as a user service:

```ini
# lorri.socket
[Unit]
Description=Lorri Build Daemon

[Socket]
ListenStream=%t/lorri/daemon.socket
RuntimeDirectory=lorri

[Install]
WantedBy=sockets.target
```

```ini
# lorri.service
[Unit]
ConditionUser=!@system
Description=Lorri Build Daemon
After=lorri.socket
Wants=lorri.socket

[Service]
ExecStart=%h/.nix-profile/bin/lorri daemon
PrivateTmp=true
ProtectSystem=strict
Restart=on-failure
WorkingDirectory=%h
```

```sh
# $HOME/.config/direnv/direnvrc
use_nix() {
  eval "$(lorri direnv)"
}
```

You don't have to manually start the service - it will be activated when ```lorri direnv``` tries to connect to the socket.

**Comment by IvanMalison** [comment]
@peterhoeg ah the socket is a nice touch. Still would be nice to be able to use nix configuration to set it up though, which could be done if it were runnable in multi-user mode.

**Comment by Profpatsch** [comment]
Yeah, I don’t think it makes sense at all to run lorri as a system service. It’s per-user.

**Comment by peterhoeg** [comment]
> which could be done if it were runnable in multi-user mode.

Just to clarify, the approach above sets up a socket per user.

**Comment by manveru** [comment]
Here's a configuration for home-manager:

```nix
{ pkgs, ... }:
let
  lorri = import (fetchTarball {
    url = https://github.com/target/lorri/archive/rolling-release.tar.gz;
  }) {};
in {
  home.packages = [ lorri ];

  systemd.user.sockets.lorri = {
    Unit = {
      Description = "lorri build daemon";
    };

    Socket = {
      ListenStream = "%t/lorri/daemon.socket";
    };

    Install = {
      WantedBy = [ "sockets.target" ];
    };
  };

  systemd.user.services.lorri = {
    Unit = {
      Description = "lorri build daemon";
      Documentation = "https://github.com/target/lorri";
      ConditionUser = "!@system";
      Requires = "lorri.socket";
      Wants = "lorri.socket";
      RefuseManualStart = true;
    };

    Service = {
      ExecStart = "${lorri}/bin/lorri daemon";
      PrivateTmp = true;
      ProtectSystem = "strict";
      WorkingDirectory = "%h";
      Restart = "on-failure";
      Environment = ''
        PATH=${pkgs.nix}/bin
        RUST_BACKTRACE=1
      '';
    };
  };
}
```

**Comment by peterhoeg** [comment]
@manveru, you probably want to change:
```
      Requires = "lorri.socket";
      Wants = "lorri.socket";
```
to
```
      Requires = "lorri.socket";
      After = "lorri.socket";
```

```Requires``` is a "stronger" version of ```Wants```.

**Comment by Moredread** [comment]
> ```
>       Environment = ''
>         PATH=${pkgs.nix}/bin
>         RUST_BACKTRACE=1
>       '';
> ```

This doesn't work correctly, as it is rendered as 

```
[Service]
Environment=PATH=/nix/store/nqpyfg13b9bpr7ihrfqhndckzmldnr5g-nix-2.2.2/bin
RUST_BACKTRACE=1
```
in the service file

```
      Environment = "PATH=${pkgs.nix}/bin RUST_BACKTRACE=1";
```

should work though.

**Comment by manveru** [comment]
I updated my comment with a better working version.

**Comment by Kiwi** [comment]
I don't use home-manager so I put this in a file lorri.nix that I import in configuration.nix and it seems to work. If anyone sees anything wrong please let me know, and hopefully someone else finds it useful! And thanks to @manveru for the original home-manager one.
```nix
{ pkgs, ... }:

let
  lorri = (import (fetchTarball {
    url = https://github.com/target/lorri/archive/rolling-release.tar.gz;
  }) {});
in
{
  systemd.user.sockets.lorri = {
    description = "lorri build daemon";
    listenStreams = [ "%t/lorri/daemon.socket" ];
    wantedBy = [ "sockets.target" ];
  };

  systemd.user.services.lorri = {
    description = "lorri build daemon";
    documentation = [ "https://github.com/target/lorri" ];
    requires = [ "lorri.socket" ];
    after = [ "lorri.socket" ];
    unitConfig = {
      ConditionUser = "!@system";
      RefuseManualStart = true;
    };

    serviceConfig = {
      ExecStart = "${lorri}/bin/lorri daemon";
      PrivateTmp = true;
      ProtectSystem = "strict";
      WorkingDirectory = "%h";
      Restart = "on-failure";
      RestartSec = "60s";
      Environment = "PATH=${pkgs.nix}/bin RUST_BACKTRACE=1";
    };
  };

  environment.systemPackages = [ lorri ];
}
```

**Comment by chreekat** [comment]
I'm trying out the user service + socket activation. So far so good :+1:

**Comment by Gerschtli** [comment]
I have an issue with this systemd config. I'm using home-manager on my ubuntu machine, but I see following errors in the log:

```
Aug 06 12:55:26 devel-one lorri[2641]: Started
Aug 06 12:55:26 devel-one lorri[2641]: Failure(
Aug 06 12:55:26 devel-one lorri[2641]:     BuildExitFailure {
Aug 06 12:55:26 devel-one lorri[2641]:         log_lines: [
Aug 06 12:55:26 devel-one lorri[2641]:             "error: file \'nixpkgs\' was not found in the Nix search path (add it using $NIX_PATH or -I), at /nix/store/pw5gwdil10ifv577zc5g6xp0r9bq4r4f-hm_profiles/php72.nix:3:13"
Aug 06 12:55:26 devel-one lorri[2641]:         ]
Aug 06 12:55:26 devel-one lorri[2641]:     }
Aug 06 12:55:26 devel-one lorri[2641]: )
```

How do you guys inject the `NIX_PATH` env var?

**Comment by chreekat** [comment]
Hey @Gerschtli, that looks like a build failure of something being evaluated, rather than an issue with lorri! The "hm_profiles" in the store path makes me suspect this has something to do with home-manager. I don't use that, so maybe somebody else can chime in.

**Comment by Gerschtli** [comment]
I don't think so.
I can reproduce it with following setup:

1. cd into empty dir
2. run `lorri init`
3. run `direnv allow .`

The logs show this:
```
Aug 06 15:59:59 devel-one lorri[2641]: Started
Aug 06 15:59:59 devel-one lorri[2641]: Failure(
Aug 06 15:59:59 devel-one lorri[2641]:     BuildExitFailure {
Aug 06 15:59:59 devel-one lorri[2641]:         log_lines: [
Aug 06 15:59:59 devel-one lorri[2641]:             "error: file \'nixpkgs\' was not found in the Nix search path (add it using $NIX_PATH or -I), at /home/tobi/test/shell.nix:2:17"
Aug 06 15:59:59 devel-one lorri[2641]:         ]
Aug 06 15:59:59 devel-one lorri[2641]:     }
Aug 06 15:59:59 devel-one lorri[2641]: )
```

.envrc:
```bash
eval "$(lorri direnv)"
```
shell.nix:
```nix
let
  pkgs = import <nixpkgs> {};
in
  pkgs.mkShell {
    buildInputs = [
        pkgs.hello
    ];
  }

**Comment by Profpatsch** [comment]
But it works if you run it manually outside of your service manager?

You probably need to set the `NIX_PATH` in your service description.

**Comment by Gerschtli** [comment]
I will give it a try tomorrow.
But do have a clue how the `NIX_PATH` is set in the systemd service on NixOS systems? Seems like a bit magic in there.. The reason for my interest is, that I want to enable `home-manager` on non-NixOS systems to have the same `nix`-specifc setup like on NixOS systems.

**Comment by chreekat** [comment]
One question comes to mind: are you running it as a user service?

**Comment by Gerschtli** [comment]
Yes, I do, configured with home-manager.. This is my expression: https://github.com/Gerschtli/home-manager-configurations/blob/master/modules/config/development/lorri.nix#L109

**Comment by Gerschtli** [comment]
It works now when I set `NIX_PATH=/nix/var/nix/profiles/per-user/$USER/channels` only for non NixOS systems. To integrate this service in `home-manager` it would be better to set `NIX_PATH` globally for all systemd user services, so we don't have to define a different service depending on the underlying OS. But I don't have a clue, how this is implemented for NixOS to work this way.

**Comment by samuelhwilliams** [comment]
I'd like to use lorri as well, and this is one of the things that would stop me picking it up. Considering that it generally works on macs, is consideration being given to lorri daemon working on macs (i.e. not depending on systemd)?

**Comment by Gerschtli** [comment]
@samuelhwilliams You don't depend on systemd, you can start `lorri daemon` in any kind of service configuration (I don't know how user services are managed on macs) or do I miss something?

**Comment by Profpatsch** [comment]
> Considering that it generally works on macs, is consideration being given to lorri daemon working on macs (i.e. not depending on systemd)?

If you are on MacOS, your service manager is `launchd`. It should be possible to write a service definition for it as well.

Two resources I found:
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html
https://www.launchd.info/

**Comment by samuelhwilliams** [comment]
> > Considering that it generally works on macs, is consideration being given to lorri daemon working on macs (i.e. not depending on systemd)?
> 
> If you are on MacOS, your service manager is `launchd`. It should be possible to write a service definition for it as well.
> 
> Two resources I found:
> 
> * https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html
> * https://www.launchd.info/

Yep, sure, I understand that. I only mention it here because it was described as the tracking issue for https://github.com/target/lorri/issues/2 - that one seemed to be a cross-platform issue, whereas this seems to be focused on linux, so was just hoping to make a point that as a Mac-user I'm still keen for a daemon, if there's a plan to add native support.

I can hack my own thing together if that's not the case.

**Comment by Profpatsch** [comment]
> hoping to make a point that as a Mac-user I'm still keen for a daemon, if there's a plan to add native support.

The daemon should already work on MacOS, please report any issues you notice with it.

**Comment by Gerschtli** [comment]
See https://github.com/rycee/home-manager/pull/799 for a service definition in home-manager.

**Comment by Gerschtli** [comment]
Is there any plan to add lorri and its systemd service definition in a NUR package? The home-manager team does not want to add something into the project if the package is not yet added to nixpkgs..

**Comment by Profpatsch** [comment]
> Is there any plan to add lorri and its systemd service definition in a NUR package?

Not from our side, no. But NUR ≠ nixpkgs, isn’t it?

**Comment by Gerschtli** [comment]
No, NUR packages enable individuals to add packages and home-manager/nixos modules in a community repository.

**Comment by grahamc** [comment]
Let's add example services in the format of:

 - a plain system `.service` and `.socket` file
 - a NixOS module system compatible user service
 - a HomeManager module system compatible user service

in to the `contrib` directory at the root of this repository. Then, link to them from the README as example ways to set up the application, and consider this ticket closed.

**Comment by pawlowskialex** [comment]
@samuelhwilliams and everyone else looking for Mac solution, this is what works for me with nix-darwin:

`~/.nixpkgs/darwin-configuration.nix`
```
{ config, pkgs, ... }:
let 
  lorri = (import (fetchGit "https://github.com/target/lorri.git") { inherit pkgs; });
in
{
  environment = {
    systemPackages = [ pkgs.direnv lorri ];

  ...

  launchd.user.agents.lorri = {
    serviceConfig.ProgramArguments = [
      "${lorri}/bin/lorri" "daemon"
    ];
    serviceConfig.StandardOutPath = "/var/tmp/lorri.log";
    serviceConfig.StandardErrorPath = "/var/tmp/lorri.log";
    serviceConfig.EnvironmentVariables = {
      PATH="${pkgs.nix}/bin";
      NIX_PATH="/nix/var/nix/profiles/per-user/root/channels";
    };
    serviceConfig.Sockets = [{
      SockPathName = "/Users/alex/Library/Caches/com.github.target.lorri.lorri.lorri/daemon.socket";
    }];
  };
}
```
It's a bit hacky cause we have to hardcode absolute socket path (it doesn't accept a relative path because it's a `types.path`, so `~` is not allowed).
Also we have to hardcode `NIX_PATH`. We can possibly fix this with by wrapping `lorri` executable with `pkgs.bash`.

**Comment by curiousleo** [comment]
Thanks for all the suggestions, everyone! I've put some of them together in this PR: https://github.com/target/lorri/pull/191. For those setups that I haven't been able to verify so far (macOS, Linux + home-manager), I've just included links to the relevant comments on this thread for the time being. That's obviously not perfect, but should give people a starting point.

**Comment by jkachmar** [comment]
So, for whatever reason, I've found that the example in [@pawlowskialex's comment](https://github.com/target/lorri/issues/96#issuecomment-545152525) didn't work for me. However after poking around GitHub a bit, I found [this example](https://github.com/iknow/nix-channel/blob/7bf3584e0bef531836050b60a9bbd29024a1af81/darwin-modules/lorri.nix) and [adapted it a little bit to my liking](https://github.com/jkachmar/dotnix/blob/1ccf9886a48e5654ab532e6239b1daa2b16bc292/config/system/lorri.nix#L27-L43).

This seems to work quite nicely, and means that I don't have to hard-code any of my paths.

---

Snip of my configuration (in case people don't want to follow links):

```Nix
{ config, pkgs, ... }:

let
  inherit (pkgs) lorri;

in {
  environment.systemPackages = [ lorri ];

  # XXX: Copied verbatim from https://github.com/iknow/nix-channel/blob/7bf3584e0bef531836050b60a9bbd29024a1af81/darwin-modules/lorri.nix
  launchd.user.agents = {
    "lorri" = {
      serviceConfig = {
        WorkingDirectory = (builtins.getEnv "HOME");
        EnvironmentVariables = { };
        KeepAlive = true;
        RunAtLoad = true;
        StandardOutPath = "/var/tmp/lorri.log";
        StandardErrorPath = "/var/tmp/lorri.log";
      };
      script = ''
        source ${config.system.build.setEnvironment}
        exec ${lorri}/bin/lorri daemon
      '';
    };
  };
}

**Comment by curiousleo** [comment]
Thanks @jkachmar! I've added a link from the docs to your comment: https://github.com/target/lorri/pull/310.

**Comment by surajbarkale** [comment]
As a minimal solution, I created `~/Library/LaunchAgents/com.github.target.lorri.plist` with following content:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.github.target.lorri</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/zsh</string>
        <string>-i</string>
        <string>-c</string>
        <string>lorri daemon</string>
    </array>
    <key>StandardOutPath</key>
    <string>/var/tmp/lorri.log</string>
    <key>StandardErrorPath</key>
    <string>/var/tmp/lorri.log</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
	<true/>
</dict>
</plist>
```

The daemon started working after executing `launchctl load ~/Library/LaunchAgents/com.github.target.lorri.plist`.

In nixpkgs I have found [xquartz](https://github.com/NixOS/nixpkgs/tree/master/pkgs/servers/x11/xquartz) and [skhd](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/skhd) create the plist as part of installation. I am trying to adopt the same solution for lorri so this process is automated.

However, lorri crashes when launched from nixpkgs shell: `env -i $(nix eval --raw '(import <nixpkgs> {}).stdenv.shell') -i -c "$(which lorri) daemon"`. I have attached the 
[crash report](https://github.com/target/lorri/files/4228344/report-339a0450-8e7d-4246-bc9a-bef1d7acc401.toml.txt) for your reference.

**Comment by nomeata** [comment]
I guess this is the right thread for such discussions. I am currently evaluationg lorri, and the first question I had was “why do I have to set up a deamon”. Many other non-system deamon-like systems (ssh control masters, pulseaudio etc.) don’t need a particular setup: They start the deamon automatically on first use, and maybe stop it after a while of disuse. Is there a particular reason why lorri can’t do the same? I could imagine that it could help adoption a lot (e.g. I’d be more willing to advocate for it in my company if I knew this would “just work”).

**Comment by curiousleo** [comment]
> Many other non-system deamon-like systems (ssh control masters, pulseaudio etc.) don’t need a particular setup: They start the deamon automatically on first use, and maybe stop it after a while of disuse. Is there a particular reason why lorri can’t do the same? I could imagine that it could help adoption a lot (e.g. I’d be more willing to advocate for it in my company if I knew this would “just work”).

Doing daemon supervision _right_ is non-trivial. On the other hand, there are a bunch of daemon supervision systems already out there that do the job really well: systemd, s6, launchd, etc.

So why reinvent the wheel? We opted instead for a design where `lorri daemon` plays well with the daemon supervisor of your choice.

Something that may not be clear from this long thread is that at least on NixOS or with home-manager, getting the service up and running is no more complicated than installing the binary: all it takes is a single line of configuration, see https://github.com/target/lorri#setup-on-nixos-or-with-home-manager-on-linux.

**Comment by nomeata** [comment]
>  with the daemon supervisor of your choice.

That already assumes a level of sophistication and geekery that raises the bar for adoption (as does using NixOS or home-manager). Not arguing that it’s technically the right choice, just saying that making things work-out-of-the box has it’s own merits.

**Comment by Profpatsch** [comment]
Personally, I like the approach [Zoom takes towards usability](https://www.theverge.com/2019/7/15/20695388/zoom-video-security-flaw-ringcentral-zhumu) ;)

But more seriously, we can kind of expect lorri users to be technical enough to write one or two lines of config. If a company wants to enforce it company-wide, they should be able to adapt our guides to their environment with ease (we made sure to make them as easy as possible to follow for the standard use-cases).

lorri does specifically not do any magic to make it as easy as possible to adapt to different environments. Thinks like double-forking have (rightly) been shown to just make life of admins hell.

**Comment by chreekat** [comment]
@nomeata suggests needing to configure a daemon hurts adoption, and @Profpatsch says we can expect lorri users to be technical enough to write a config file. But these are not contradictory statements! I have extremely competent colleagues who are choosing not to use lorri, in part because it requires setting up a daemon. I am also reluctant to build any contributor tooling around it for the same reason.

But for our use cases, perhaps something like xzfc/cached-nix-shell is a better fit?

If lorri *could* choose some compromise that allowed for a Just Works workflow, I do think it would help. Actually, does lorri have a one shot mode? Could it behave similarly to cached-nix-shell?

**Comment by curiousleo** [comment]
> Actually, does lorri have a one shot mode? Could it behave similarly to cached-nix-shell?

Check out `lorri shell --help`.

**Comment by Profpatsch** [comment]
Also, `lorri watch --once`.

**Comment by Profpatsch** [comment]
> If lorri _could_ choose some compromise that allowed for a Just Works workflow, I do think it would help. Actually, does lorri have a one shot mode? Could it behave similarly to cached-nix-shell?

Starting the daemon *is* the Just Works workflow.

**Comment by tricktron** [comment]
Lorri has been added to nix-darwin: https://github.com/LnL7/nix-darwin/pull/222.

You can install it with:
```bash
environment.systemPackages = with pkgs; [ direnv ];
services.lorri.enable = true;
```
and the daemon will be configured automatically.

@curiousleo Could you add this to the README?

**Comment by Profpatsch** [comment]
@tricktron do you want to submit a PR with the documentation?

**Comment by Profpatsch** [comment]
Thanks to @jkachmar, documented in #479

**Comment by tricktron** [comment]
@jkachmar Thank you for jumping in and documenting it.

**Comment by pwm** [comment]
@surajbarkale did you figure out why lorri crashed there? I'm on macOs + home-manager but not nix-darwin and would like to use your method.

**Comment by surajbarkale** [comment]
I believe it was because NIX_PATH was not set up properly in zsh. You
should give it a try and find out. I haven't used this setup since last
year.
