### ISSUE TITLE
lorri+direnv breaks curl etc. by setting SSL_CERT_FILE

### ISSUE THREAD

**Issue by Shados** [target/lorri#98]
`nix-shell` has [some logic](https://github.com/NixOS/nixpkgs/blob/a8a45b4109069892ec33c1921ef200ddd5560bd9/pkgs/stdenv/generic/setup.sh#L649-L657) to *not* set `SSL_CERT_FILE` to a bogus file (if not using `--pure`).

`lorri` unfortunately sets it, causing `curl`, `git`, `wget`, etc. to be unable to connect to HTTPS websites due to not having a certificate store to verify SSL authenticity against. I haven't looked into why, at this point, but I guess (given the old workaround mentioned below does not work) there are some oddities in how you construct the shell?

The old workaround from when this was an issue with `nix-shell` was: set `SSL_CERT_FILE` outside of the `nix-shell` environment before loading it. Which doesn't work; you can workaround the issue in lorri by explicitly setting the variable inside of the `shell.nix`, e.g:
```
mkShell {
  ...
  SSL_CERT_FILE = "/etc/ssl/certs/ca-bundle.crt";
  ...
}
```

**Comment by Profpatsch** [comment]
What does your `shell.nix` look like?

**Comment by Shados** [comment]
Kinda complicated surroundings, but ultimately boils down to basically this:
```nix
mkShell {
  name = "foo-shell";
  buildInputs = [
    foo
  ];
  shellHook = ''
    export FOO="$variable_set_by_earlier_hook_in_buildinputs"
  '';
}
```

**Comment by grahamc** [comment]
What if we gave you a way to tell Lorri to not set SSL_CERT_FILE, like setting `lorriDontSet = [ "SSL_CERT_FILE" ];`

**Comment by bbigras** [comment]
> What if we gave you a way to tell Lorri to not set SSL_CERT_FILE, like setting lorriDontSet = [ "SSL_CERT_FILE" ];

I have the same problem. This change would be fine for me.

At first I thought it would be bad to "break" accessing https sites by default but it seems `nix-shell --pure` does it too.

**Comment by bbigras** [comment]
In my case I also had problem connecting to HTTPS websites using CAs from `security.pki.certificates`. It seems fine if I unset both `SSL_CERT_FILE` and `NIX_SSL_CERT_FILE`.

**Comment by Shados** [comment]
@grahamc that works, but obviously I'd prefer a single `shell.nix` to work the same with either tool.

@bbigras if you're using `nix-prefetch-git` inside of a lorri environment, you'll also need to unset `GIT_SSL_CAINFO`, I expect.

**Comment by Profpatsch** [comment]
> that works, but obviously I'd prefer a single `shell.nix` to work the same with either tool.

I’m sorry, but we can’t guarantee the exact same semantics for everything (see https://github.com/target/lorri/issues/91 for example).

But in this case we should try our best to keep in sync with the impure shell.

**Comment by scoates** [comment]
FWIW (in case it helps anyone), I seem to have managed to work around this by unsetting `SSL_CERT_FILE` in my `.envrc`:

```bash
eval "$(lorri direnv)"
unset SSL_CERT_FILE
```

**Comment by grahamc** [comment]
In Lorri we set IN_NIX_SHELL=1, maybe setting it to `impure` is the solution. However, none of my lorri shells set SSL_CERT_FILE, so I haven't seen this before. What more specifically does your shell.nix contain?

**Comment by bbigras** [comment]
In my case I try to push to a git repo which use our company CA (set with security.pki.certificates in configuration.nix).

**Comment by teehemkay** [comment]
FWIW I think I'm seeing the same issue. I'm using `nix-darwin` and a vanilla `shell.nix` that just add `nodes`. I can no longer access GitHub repositories when I'm in an environment setup by Lorri.
I get the following error message: 
`fatal: unable to access 'https://github.com/teehemkay/<some-repo-path>.git/': SSL certificate problem: unable to get local issuer certificate`

I've tested using curl in verbose mode and it also fails:

```
* allocate connect buffer!
* Establish HTTP proxy tunnel to github.com:443
> CONNECT github.com:443 HTTP/1.1
> Host: github.com:443
> User-Agent: curl/7.65.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* error setting certificate verify locations:
  CAfile: /no-cert-file.crt
  CApath: none
curl: (77) error setting certificate verify locations:
  CAfile: /no-cert-file.crt
  CApath: none
```

Per @bbigras and @scoates suggestions above, I've unset both `SSL_CERT_FILE` and `NIX_SSL_CERT_FILE` in my `.envrc` and now access to https website seems to be working as before.

**Comment by bbigras** [comment]
@teehemkay I think you can also add `cacert` in your shell.nix's buildInputs to fix your github issue.

**Comment by johnae** [comment]
This does seem like a usability issue. Basically what I've found is that as soon as I started using lorri I could no longer curl or wget anything from within nix shells / direnv and lorri seems to do something different. Basically I see this set in the environment:

```
env | grep SSL
NIX_SSL_CERT_FILE=/no-cert-file.crt
SSL_CERT_FILE=/no-cert-file.crt
```

Not sure why lorri would do that but using only nix-shell with direnv didn't do that.

**Comment by johnae** [comment]
A `shell.nix` looking like this is enough really to create this scenario:

```
with import <nixpkgs> {};

pkgs.mkShell {
  buildInputs = [
                  nodejs-10_x
                ];
}
```

**Comment by Profpatsch** [comment]
@johnae Can you try out lorri on master? (clone the lorri repo, run `lorri self-upgrade local /path/to/lorri/checkout`)

It should have been fixed by https://github.com/target/lorri/pull/164 (at least it looks that way from my end, also NixOS).

**Comment by johnae** [comment]
Yeah @Profpatsch - using master now instead of the rolling-release branch and it's fixed there. Thanks!
